### ISSUE TITLE
Use importScripts to import Ammo in src/physics/worker.js

### ISSUE THREAD

**Issue by Carnewal** [WhitestormJS/whitestorm.js#106]
Describe your issue here.

###### Version:
10

###### Issue type:
 - [x] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Ubuntu
   - [x] Chrome

</details> 
When I try running the World/Sphere demo I get `Uncaught ReferenceError: _whsAmmo2 is not defined` in a webpack project where I installed whitestorm through npm. 
I believe this has something to do with babel not correctly compiling `import Ammo from 'whs-ammo';` to something usable by the WebWorker. 

I propose removing the import and instead use importScripts and RequireJS. Thoughts?

**Comment by sasha240100** [comment]
@Carnewal You mean **basic/helloword** demo? Is this issue happens only when installing from npm or from github too?

**Comment by sasha240100** [comment]
@Carnewal Uploaded a dev version, use `npm install whitestormjs@dev`. Can you try that?

**Comment by Carnewal** [comment]
Only made it worse :smile: 
1. Please save 'three-obj-loader' to the package.json
2. ```
Module not found: Error: Cannot resolve 'file' or 'directory' ../core/line in ...l/whitestormjs-webpack-test/node_modules/whitestormjs/lib/physics/meshes
 @ ./~/whitestormjs/lib/physics/meshes/ropeMesh.js 24:12-35
``` No idea why? Everything is there .. weird

Please see https://github.com/Carnewal/whitestormjs-webpack-test

**Comment by sasha240100** [comment]
@Carnewal Ah, yep, i forgot to exclude it from code, `three-obj-loader` shouldn't be in core [I fix it with next commit].
About second problem - it seems error is because i have `Line.js` instead of `line.js`. I'm going to fix that now, should work. You may copy that from github (it will take more time if i will upload it to npm each time)

**Comment by Carnewal** [comment]
Will do!

**Comment by sasha240100** [comment]
@Carnewal Btw, what project are you going to build? Tell us more:)

**Comment by sasha240100** [comment]
@Carnewal Ready: https://github.com/WhitestormJS/whitestorm.js/commit/34e2a19b7a6f90923723fec5b468c154817d5db8

Haven't uploaded to npm yet. Just copy all files you need, i will ping you when it is uploaded to npm

**Comment by Carnewal** [comment]
It's for my bachelor thesis about local multiplayer gaming. I'd like to make a demo to show what's possible, that's why WhitestormJS looks promising to easily create a game with physics. 

I added the dev repo to my dependencies ([(repo)](https://github.com/Carnewal/whitestormjs-webpack-test)). Line problem is fixed but the `Uncaught ReferenceError: _whsAmmo2 is not defined
2app.bundle.js:79` error persists. 

Maybe this is of use http://requirejs.org/docs/api.html#webworker

**Comment by sasha240100** [comment]
@Carnewal I see, you are trying to use whitestorm.js through es6 modules. The thing is that whitestorm.js uses webpack already with it's custom settings. Do you really need webpack for whitestorm.js?

**Comment by sasha240100** [comment]
I mean what if you will just add it's build using script tag?

**Comment by sasha240100** [comment]
@Carnewal Any updates there? May I close it?

**Comment by sasha240100** [comment]
@Carnewal Some updates:
 Using files from `lib` is now deprecated. Right now i see only one an the best way is to you through script tag. Just include that file from `build` folder. If you have any other ideas (For example how can we make it modular in rational way) - you may ask me.

**Comment by t4r0** [comment]
hey @sasha240100  so far I just replaced the webpack configurations on my fork, but i don't think it's ready yet :disappointed:, since webpack won't export the WHS global var, when setting the whole thing as a UMD module.

@Carnewal you will be able to use whitestorm as an npm module with the ES6 features by pointing your package.json to my fork. While we think of a nice strategy to export the library before the new release :simple_smile:

**Comment by sasha240100** [comment]
@Carnewal This should help you: https://github.com/WhitestormJS/test-whitestorm-webpack
