### ISSUE TITLE
Add support for Three.EffectComposer and Three.ShaderPass

### ISSUE THREAD

**Issue by typedef42** [WhitestormJS/whitestorm.js#107]
Hi,
Support for EffectComposer to be able to render nice graphic effects with ShaderPass would be nice. It seams that you though about it in WHS.World as there is a this._composer in start() but doesn't work yet.

Do you have a roadmap for this feature, and/or already though about how to deal with it ? 

###### Version:
 - [x] r10 (dev)
 - [ ] r9
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@typedef42 Sure, will check it today or tomorrow. Is there some other postprocessing api i should check with it?

**Comment by typedef42** [comment]
well, one use case I have would be to use additional RenderTarget to compose some glow effect on top of my stardard render buffer. 

The way I use it with Three.js is that : 
1. I create another Three.camera and another Three.scene that contains only glow meshes I use in my shaders pass. 
2. Then I create a new WebGLRenderTarget (witch I belive create a new FrameBuffer under the hood). 
3. I bind this RenderTarget to the WebGLRenderer with a Three.EffectComposer
4. I add one RenderPass and several ShaderPass to my composer.

Here is a snippet of what it would look like in pseudo Three.js code :
```
// in my case only need one renderer instance, don't kwow if one could need more than one...
this.renderer = new THREE.WebGLRenderer();
this.dom.appendChild(this.renderer.domElement);

// ---------------------------------------
// Render to screen buffer
this.scene = new THREE.Scene();
this.camera = new THREE.Camera(...);

const renderModel = new THREE.RenderPass(this.scene, this.camera);
this.mainRenderTarget = new THREE.WebGLRenderTarget(size...);

// this would get the output of my Glow RenderTarget defined bellow
this.glowResultPass = new THREE.ShaderPass(AdditiveShaderForExample);
this.glowResultPass.uniforms['tAdd'].value = this.glowComposer.renderTarget1;

this.mainComposer = new THREE.EffectComposer(this.renderer, this.mainRenderTarget);
this.mainComposer.addPass(renderModel);
this.mainComposer.addPass(new THREE.ShaderPass(AntialiasingShader));
this.mainComposer.addPass(this.glowResultPass);
// ---------------------------------------


// ---------------------------------------
// Render Target 1 buffer (for glow for example)
this.glowScene = new THREE.Scene();
this.glowCamera = new THREE.Camera(...);

this.glowRenderTarget = new THREE.WebGLRenderTarget(size);
const glowRenderModel = new THREE.RenderPass(this.glowScene, this.glowCamera);
const glowPass1 = new THREE.ShaderPass(...);
const glowPass2 = new THREE.ShaderPass(...);
const glowPass3 = new THREE.ShaderPass(...);

// this is where you bind the renderer with the rendertarget. In my case I bind it to the main and only renderer, but I guess i could be another renderer.
this.glowComposer = new THREE.EffectComposer(this.renderer, this.glowRenderTarget);
this.glowComposer.addPass(glowRenderModel);
this.glowComposer.addPass(glowPass1);
this.glowComposer.addPass(glowPass2);
this.glowComposer.addPass(glowPass3);
// ---------------------------------------
```

The way I would implement that into whitestorm, I can see two options :

1/ Wrap the whole process in a new WHS core class. Some king of WHS.PostProcessor for example. (less elegant I think and weird since a PostProcessor will need its own scene and camera...)

2/ Modify the WHS.World class enought that it can handle a WebGLRenderer or a WebGLRenderTarget (or both at the same time) and a EffectComposer and RenderPass/ShaderPass etc. It would also provide a way to easly instanciate multiple WHS.World and bind the WebGLRender of the 'main' WHS.World to the others.

I think it make sense since I basically render different Worlds (one for glow, one for occlusion etc) with different kind of meshes, that I mix one on top the other at the end in the main World composer.

This is the kind of rendering I end up with, and why I need this feature to switch to WHS. [image](https://img42.com/jiXX2)

Don't known if I'll have the time to fork and make a try at this weekend, but if you have a look at it, it's awesome !

**Comment by sasha240100** [comment]
@typedef42 Effect composer is that thing that lack in whitestormjs currently. Nice that you want to implement it, me too.
So, you need to follow some simple rules (make a pull request):
 1. Make all your changes in `dev` branch. I will later merge it to master.
 2. You may add new classes (no problems with that).
 3. You may make some pull requests (different ways of implementation). We will later choose the best one (most rational).

Also, can you upload a repo that you are working on to GitHub (and share a link here)? We will later make a showcase section and put all projects made using whitestormjs there. Thanks for all that work that you do to help this project grow:)

**Comment by typedef42** [comment]
ok, I'll take a look at it when I can, following the repo rules, no problem.
I first need to 'revive' this old project using THREE r60 and es5, and migrate it to ESNext and up to date THREE.js / whitestormjs

**Comment by sasha240100** [comment]
@typedef42 Some things / commands that will be useful for you in development and testing:
 - run `npm install` fisrt (install all npm modules, even devDependencies, check that your `NODE_ENV` is "development" before that).
 - run `gulp dev`. It is a universal command for development:) It will run all examples by `localhost:8080`. You can changes whitestorm.js source (`src/framework`) and examples source at `src/examples/`, everything will be compiled immediately.

For other CLI commands [check this](https://github.com/WhitestormJS/whitestorm.js/blob/master/.github/CONTRIBUTING.md#cli)

**Comment by typedef42** [comment]
Thanks, i'm already familiar with npm and gulp, i'm using them with node.js, aurelia.io/jspm in my build toolchain :)
I quickly pulled the dev branch to test, it's working but I think you miss a dep in your package.json though, its babel-polyfill.
Nice for the CLI readme, it's easier than read the gulpfile !

**Comment by sasha240100** [comment]
@typedef42 I made some updates in `dev` branch. Merge them please if you already started.

**Comment by sasha240100** [comment]
@typedef42 Any updates on your project?

**Comment by typedef42** [comment]
Hi, I started to work on something, it is more work than what I estimated at first but totally do-able, problem is that I also lost internet at home for now :/

I'll keep you informed as soon as I have a working prove of concept.

**Comment by sasha240100** [comment]
Hello, @typedef42. I just published r11 which is more stable than before. But we still aren't able to support that feature you are talking about.
I want to add this in the nearest time so you may help me with that by doing one from this three things:

 - Describe your needs and what should I implement. (I will take care about implementing)
 - Fork this repo, edit sources, check if all this stuff works properly and make a pull request.
 - Join our team as an open-source developer and help us committing to the dev branch.

Thanks!

**Comment by typedef42** [comment]
Hi @sasha240100,

Sorry not giving you feedback sooner, bad timing for me. I've already forked and started an implementation of a PostProcessor class that can be 'attached' to a World instace and that wrap Three RenderTarget, EffectComposer and *Pass.. The aims is beeing to be able to recreate all the postprocessing examples from official three.js repo.

For now it hasn't impacted the World class a lot, so I'll merge back the release you just made into my fork to stay up to date. (i've not pushed on my fork yet, as not everything working yet)

I hope I will have some basic working implementation of the PostProcessor soon (this week, may be next week if I can't keep up with work), but I have a question concerning dependencies : as Three.EffectComposer, Three.RenderPass/ShaderPass are not part of the THREE.js core lib, but rather part of the three.js examples folder, how do you want to deal with theses dependencies ? 

1/ we have to embed EffectComposer and *Pass source code in WHS (and keep it up to date..)
or
2/ we have to separate post processing from WHS core, and make this feature some kind of external plugin that itself embed the extra three.js code deps 

Tell me what you think about that,
cheers,

**Comment by sasha240100** [comment]
@typedef42 Second option sounds good. We can just reserve a place for ability to add postprocessing in World class and all other stuff with THREE.EffectComposer will be added as a plugin.

**Comment by sasha240100** [comment]
@typedef42 I made a project where i needed glow and faced the same problem (no api for THREE.EffectComposer). So now i really understand you. Let's fix this problem this week. Okay? Tell me what you've done or what you need to do.

**Comment by typedef42** [comment]
Ok, I have a basic working version. you can check out an example there :
https://github.com/typedef42/whitestorm.js/blob/dev/src/examples/post-processing/basic-glitch/script.js#L260

It is still very much work in progress, (resizing is not working yet, and I did not tested multiple world / PostProcessor example for complex rendering)

If I summarize, I ended up re-implementing Three EffectComposer and Pass mecanism in es6 and wrapped their use in a PostProcessor class that can be attached to a world instance.

I did all of that inside the post-processing folder to avoid weird dependencies with Three/examples folder. IMO Scene composition is important enought that it should be part of core engine source code, not just part of the example folder... (never understood why they did that in Three)

**Comment by sasha240100** [comment]
@typedef42 Awesome! Make a pull request now. I'll review it and maybe make some changes and notify you anyway.

We are going to make a plugin registry (like gulp has), but for whitestormjs with a lot of interesting stuff that can't be in core of framework but is very common for developers! So be in touch with us:)

**Comment by sasha240100** [comment]
@typedef42 Merged.

**Comment by sasha240100** [comment]
@typedef42 Cool! Can you please describe the API?:) You may add your classes to docs: https://github.com/WhitestormJS/whitestormjs.github.io/tree/editing/source/includes
- We use this template for docs: https://github.com/lord/slate
- or add some unit tests, so i can make docs by them.

**Comment by typedef42** [comment]
wow that was fast ! 
I put the kids to bed and start working on the doc/api, and adding more complex examples of post processing :).

**Comment by sasha240100** [comment]
@typedef42 I made some changes: https://github.com/WhitestormJS/whitestorm.js/commit/6bfed1dcc0de28e00e1aac5e98a90e665101cc73

- Removed `lodash` (replaced) - less Kb
- Removed polyfill  for es6 promises. (babel already do this).
- And please check that i replaced `pass.name` with `passIndicator.name` https://github.com/WhitestormJS/whitestorm.js/commit/6bfed1dcc0de28e00e1aac5e98a90e665101cc73#diff-f4820f54bc8ca13f3497930c9e462b6cR52

I see that resizing is not implemented yet. I give you access to repo so you can add changes without pull request and test them. Sending you an invite! Check your Email.

**Comment by typedef42** [comment]
looks fine to me, i'm going to test / documenting that now.
