### ISSUE TITLE
Cannot read property 'ConvexMesh' of undefined with WHS.Text

### ISSUE THREAD

**Issue by Tzikas** [WhitestormJS/whitestorm.js#108]
I'm able to get the examples working and when I paste the following in the playground it works fine, but on my local machine I get Cannot read property 'ConvexMesh' of undefined 

`const text = new WHS.Text({
  geometry: {
    text: 'hello world',
    parameters: {
      font: 'assets/fonts/gentilis_bold.typeface.js',
      size: 20,
      height: 5,
      curveSegments: 6
    }
  },

  mass: 10,

  material: {
    color: 0x00ff00,
    kind: "lambert"
  },

  pos: {
    x: -40,
    y: 20,
    z: 0
  }
});

text.addTo(world);`

###### Version:
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@Tzikas What version of whitestormjs are you using? Do you use a file in `build` folder or compile with webpack?

**Comment by sasha240100** [comment]
ConvexMesh is a class of Physijs (built-in physics library). It seems like this library is undefined

**Comment by Tzikas** [comment]
i did npm install whitestormjs and then added to this to index.html <script src="node_modules/whitestormjs/build/whitestorm.js"></script>

**Comment by Tzikas** [comment]
Using a cdn seems to work ` <script src="https://cdn.jsdelivr.net/whitestormjs/latest/whitestorm.min.js"></script> `

**Comment by Tzikas** [comment]
Now i'm running into a lot more problems 
`whitestorm.min.js:7 No rabbits for the box. (arguments) ["object", "undefined"]WHS.API.merge @ whitestorm.min.js:7(anonymous function) @ whitestorm.min.js:7value @ whitestorm.min.js:7(anonymous function) @ index.js:224
three.js:8806 THREE.Object3D.add: object not an instance of THREE.Object3D. undefinedadd @ three.js:8806window.Physijs.Physijs.Scene.add @ physi.js:825WHS.API.merge @ whitestorm.min.js:7(anonymous function) @ whitestorm.min.js:7value @ whitestorm.min.js:7(anonymous function) @ index.js:224
whitestorm.min.js:7 Cannot read property '_physijs' of undefined(anonymous function) @ whitestorm.min.js:7value @ whitestorm.min.js:7(anonymous function) @ index.js:224
whitestorm.min.js:7 Uncaught (in promise) undefined(anonymous function) @ whitestorm.min.js:7value @ whitestorm.min.js:7(anonymous function) @ index.js:224
favicon.ico:1 GET http://localhost:8080/favicon.ico 404 (Not Found)
three.js:18506 THREE.FontLoader: typeface.js support is being deprecated. Use typeface.json instead.
three.js:34630 THREE.ShapeUtils: Duplicate point 12.36:4.42 3783
three.js:34630 THREE.ShapeUtils: Duplicate point 11.74:-0.8200000000000001 4490`

**Comment by Tzikas** [comment]
This is my js 
`const world = new WHS.World({
  autoresize: true,

  background: {
    color: 0xffffff
  },

  gravity: { // Physic gravity.
    x: 0,
    y: -100,
    z: 0
  },

  camera: {
    z: 50
  }
});

const sphere = new WHS.Sphere({ // Create sphere object.
  geometry: {
    radius: 3
  },

  mass: 10,

  material: {
    color: 0x00ff00,
    kind: 'basic'
  }
});

sphere.addTo(world);
sphere.getNative(); // Returns THREE.Mesh of this object.




const text = new WHS.Text({
  geometry: {
    text: 'hello world',
    parameters: {
      font: 'Funkrocker.js',
      size: 20,
      height: 5,
      curveSegments: 6
    }
  },

  mass: 10,

  material: {
    color: 0x00ff00,
    kind: "lambert"
  },

  pos: {
    x: -40,
    y: 20,
    z: 0
  }
});

text.addTo(world);
world.start(); // Start animations and physics simulation.`

**Comment by sasha240100** [comment]
@Tzikas We need to fix CDN. You may download and use [one from dev branch](https://github.com/WhitestormJS/whitestorm.js/blob/dev/build/whitestorm.js) till i release r11 version (should be soon)

**Comment by sasha240100** [comment]
The one from dev branch has some other fixes and i tested it in [StreetBasketballGame](https://github.com/WhitestormJS/StreetBasketballGame) - I use WHS.Text there too, works. Let me know if it works

**Comment by Tzikas** [comment]
Nice.  Yeah that branch works better already.  I can get a basic sphere falling but when include text i get `THREE.FontLoader: typeface.js support is being deprecated. Use typeface.json instead.
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 12.36:4.42 3783
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 11.74:-0.8200000000000001 4490`

**Comment by Tzikas** [comment]
I'll try json format

**Comment by sasha240100** [comment]
@Tzikas Those come from three.js. You may use this as a crib sheet

**Comment by sasha240100** [comment]
@Tzikas Does this help?

**Comment by Tzikas** [comment]
Sort of.  I can run your game locally (nice work btw), but I'm just trying to get a very simple hello world and you have a lot going on in that repo.  I think I may just be incorrectly importing Three.  So I'm gonna try that right now.

**Comment by Tzikas** [comment]
I got it.  It looks like it's a font issue

THREE.FontLoader: typeface.js support is being deprecated. Use typeface.json instead.
2whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 19.46:1.48 2212
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 17.58:3.48 2561
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 17.16:1.78 2692
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 16.52:6.140000000000001 2693
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 16.46:6.2 2694
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 31.620000000000005:3.02 910
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 44.540000000000006:3.02 910
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()

**Comment by Tzikas** [comment]
Yours 1.js gave me a unxepcted token ) and my other ran into an infinite loop.  I tried a third and it worked, but it's rendering very slowly.

**Comment by sasha240100** [comment]
@Tzikas You shouldn't import three.js with whitestorm.js. Whitestorm.js already has three.js in it's build. The reason of why we have three.js in whitestorm.js is that three.js API always changes and some version of three.js may not work with whitestorm.js wrapper and that's why we include specific one in whitestorm.js build. 

*If you have such code:*

```javascript

<script src="js/three.js"></script>
<script src="js/whitestorm.js"></script>

```

It's incorrect. In this example three.js is overwritten by three.js in `whitestorm.js`, so use: 

```javascript

<script src="js/whitestorm.js"></script>

```

**Comment by sasha240100** [comment]
@Tzikas Can you upload your code to github? (it's better if github pages) I will check it for errors and leave some notes

**Comment by sasha240100** [comment]
I know that's difficult to understand versioning in whitestorm.js, it can be confusing, but next whitestorm.js (**r11**) will be with unit testing so i can say it works. Now many parts of it haven't been correctly tested (because there is a lot of work, many classes used in this framework)

**Comment by Tzikas** [comment]
Thank you.  https://github.com/Tzikas/whiteStormHelloWorldText

**Comment by Tzikas** [comment]
It seems to work now, but it is quite laggy.

**Comment by sasha240100** [comment]
@Tzikas Use http://gero3.github.io/facetype.js/ to generate a font

**Comment by sasha240100** [comment]
Should help

**Comment by Tzikas** [comment]
I did.

**Comment by Tzikas** [comment]
Getting this `physi.js:15 Uncaught ReferenceError: THREE is not defined(anonymous function) @ physi.js:15(anonymous function) @ physi.js:1403
whitestorm.js:34787THREE.WebGLRenderer 79
whitestorm.js:28460 THREE.FontLoader: typeface.js support is being deprecated. Use typeface.json instead.
2whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 19.46:1.48 2212
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 17.58:3.48 2561
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 17.16:1.78 2692
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 16.52:6.140000000000001 2693
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 16.46:6.2 2694
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 31.620000000000005:3.02 910
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 44.540000000000006:3.02 910
2whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 114:17.94 789
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()
whitestorm.js:44584 THREE.ShapeUtils: Duplicate point 125.8:3.02 910
whitestorm.js:44073 THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()`

**Comment by sasha240100** [comment]
@Tzikas Can you please remove `node_modules` folder from repo? Simply add `node_modules/` to .gitignore
We'll get back to npm and node when i'll fix it.

I can't clone that repo because of `node_modules` (long pathes)

**Comment by Tzikas** [comment]
ok i removed it

**Comment by sasha240100** [comment]
@Tzikas Uploaded a one for testing with npm. Use `npm install whitestormjs@dev`

**Comment by sasha240100** [comment]
This will let you download the same build as is now in dev branch

**Comment by sasha240100** [comment]
@Tzikas You can test it while i clone your branch

**Comment by Tzikas** [comment]
I'm a little confused.  I ran npm install whitestormjs@dev in my local folder, and then http-server to run it on localhost:8080, but I have the same problem.  Was I suppose to do something else?

**Comment by sasha240100** [comment]
@Tzikas Okay, now i see your errors 

![image](https://cloud.githubusercontent.com/assets/7657429/17951447/dae72fce-6a6a-11e6-9005-1a5c804e556e.png)

**Comment by Tzikas** [comment]
Yes exactly.

**Comment by Tzikas** [comment]
I tried another font and got this error `Infinite Loop! Holes left:1, Probably Hole outside Shape!` and only that error.

**Comment by sasha240100** [comment]
@Tzikas Okay, first of all you are loading are trying to load a 6.66 👿 MB file. 1)  three.js then process a lot of vertices and polygons. 2) 66.6 = 666 devil number, isn't it? 👿 
Second thing is that you make it a physics object, this ammount of vertices for physics object is a lot. (really a lot)

**Comment by sasha240100** [comment]
That is regarding you said it is slow

**Comment by Tzikas** [comment]
LOL thanks.

**Comment by sasha240100** [comment]
You can try using three.js natively, i'm sure you'll get the same result

**Comment by Tzikas** [comment]
Is there a very basic font, that I could use?

**Comment by sasha240100** [comment]
@Tzikas Those errors in console are not so bad. They are just errors of compiling your font to .js font (for three.js) I had them too, it's okay. 

You may also enable this option. Sometimes it reduces the amount of errors.
![image](https://cloud.githubusercontent.com/assets/7657429/17951579/e93e42dc-6a6b-11e6-9b12-ecfad1edbdd9.png)

**Comment by Tzikas** [comment]
That is faster and working without error.  Thanks.

**Comment by sasha240100** [comment]
@Tzikas One more advice: reduce the amount of `curveSegments`. Right now you have 6 of them, you may set to 1.

**Comment by Tzikas** [comment]
Any other ideas on how to speed it up?

**Comment by Tzikas** [comment]
Cool.  Thank you.

**Comment by sasha240100** [comment]
I made it faster 6 times with setting curveSegments to 1.

**Comment by sasha240100** [comment]
@Tzikas May i close this issue?

**Comment by Tzikas** [comment]
Yeah I believe unless you have any other ideas on rendering this faster, than I'm satisfied.  Thank you very very much.

**Comment by sasha240100** [comment]
```javascript

const text = new WHS.Text({
  geometry: {
    text: 'hello world',
    parameters: {
      font: 'ironBrine.js',
      size: 20,
      height: 5,
      curveSegments: 1 // !!!!!
    }
  },

  physics: false, // Turn physics off.

  material: {
    color: 0x00ff00,
    kind: "lambert"
  },

  pos: {
    x: -40,
    y: 20,
    z: 0
  }
});

````

**Comment by Tzikas** [comment]
Yeah but I want the letters to crash into one another hahaha.

**Comment by sasha240100** [comment]
@Tzikas You still have a large font, you may find other less-detailed one. Try with one i used as 1.js in my example.

**Comment by sasha240100** [comment]
@Tzikas It's possible, but this way you may have split your letters into separate meshes. Also trick with using different shapes for graphic and physics should help. I'll explain:

With this trick you use different geometries for physics shape and three.js mesh. Simplified one you apply to physics to achieve best performance.

![image](https://cloud.githubusercontent.com/assets/7657429/17951749/4e450cdc-6a6d-11e6-9851-0ad7a086a574.png)

How can you do it with text? Here is what i suggest:

 - Make a WHS.Text with simplified letter geometry. // This will make such for physics too.
 - Make a high-resolution (as you want) three.js geometry of letter.
 - Apply this geometry to `myLetter.getNative().geometry`
 - **Profit!** Now you have a simple geometry for collisions and complex for graphics!
