### ISSUE TITLE
Running app from external js file

### ISSUE THREAD

**Issue by mrinalpande** [WhitestormJS/whitestorm.js#110]
Whenever I try to run the app from an external js file it gives me a error.  But when I use the same code inside my html file it works fine. I have tried it with npm install and the github repo.  The error is as follows:

_

> Uncaught TypeError: Cannot read property 'style' of null (World.js:184)

_

 Issue type:
 - [x] Bug

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Firefox

</details>

**Comment by sasha240100** [comment]
Hello, @mrinalpande, can you attach a link to your sources here? (A GitHub repo or etc.) I will check whitestormjs for that issue in 15 mins once my PC is on

**Comment by sasha240100** [comment]
@mrinalpande **WHS.World** needs to have it's own DOM element in which it will append a canvas element. By default when we init world like `new WHS.World()` (without additional parameters) - WHS.World takes `document.body` as a container.

Regarding your problem - it seems that your `document.body` is **null**. You may add _contatiner_ property when creating a world. 

```javascript
const world = new WHS.World({
  // ...
  container: myDOMelement
});
```

P.s.: Also debug your `document.body` in the environment you do a `new WHS.World()`...

**Comment by mrinalpande** [comment]
But when I try it inside my html document inside the <script> tags it works with out any addition to the DOM element or any addition to the code. For 

> document.body

 being null I see that can be a problem but when I work around with no elements on the canvas and script inside the html it works fine.

**Comment by sasha240100** [comment]
@mrinalpande Ah, that's simple: simply add your `<script>` tag in the end of `<body>` _(before `</body>`)_. It can be beacuse you load WHS.World before DOM is ready. Can you upload a code to github pages?

**Comment by mrinalpande** [comment]
It's the example from the site here I made a repo. 

https://github.com/mrinalpande/whsapp

**Comment by sasha240100** [comment]
@mrinalpande I'll make a pull request with fix

**Comment by sasha240100** [comment]
@mrinalpande https://github.com/mrinalpande/whsapp/pull/1
Merge this.

**Comment by mrinalpande** [comment]
Yup making it after the body worked...
Thanks
Will start working on whitestorm repo 
see you soon

**Comment by sasha240100** [comment]
@mrinalpande Btw, what are you going to create? or just trying it?

**Comment by electron0zero** [comment]
@mrinalpande can we close this issue ?

**Comment by mrinalpande** [comment]
Well I was trying it at first now. I am thinking on making something and contributing to the repo...
Thanks @electron0zero  for recommending it to me...
Sure this issue is resolved

**Comment by sasha240100** [comment]
@electron0zero Yes, it is solved so I close it. @mrinalpande join our slack http://whslack.herokuapp.com or email me
