### ISSUE TITLE
The DOF constraint is missing

### ISSUE THREAD

**Issue by kaelhem** [WhitestormJS/whitestorm.js#111]
The "degree of freedom" constraint existing in Physijs seems to have been omitted during refactor of the r10 release. Is there a particular reason to haven't includes it ?

**Comment by sasha240100** [comment]
@kaelhem We haven't yet developed API for that. It will be ready probably in r11, but now you may use it as a part of Physijs. You can get native object through `shape.getNative()` and apply a constraint from Physijs object. Ping me when it is done or you have a problem with that.

**Comment by sasha240100** [comment]
If you are including whitestormjs using script tag - **Physijs** should be available as a global variable.

**Comment by sasha240100** [comment]
@kaelhem You may also check the one from `dev` branch. Do you face the same problem there?

**Comment by sasha240100** [comment]
@kaelhem Okay, now i understood the problem. There are no constraints included yet. I'll make today a new build with them included and attach a link there.

**Comment by kaelhem** [comment]
@sasha240100 wow! it sounds great :)

**Comment by sasha240100** [comment]
@kaelhem I added DOF constraint in https://github.com/WhitestormJS/whitestorm.js/commit/22aeb190c295f88cdd0ec66bbaa56b3c94922584
But it seems it framework doesn't work in production because Ammo.js is processed by UglifyJS second time. Trying to fix that, i'll keep you in touch

**Comment by sasha240100** [comment]
@kaelhem Seems like fixed. Use this one: https://raw.githubusercontent.com/WhitestormJS/whitestorm.js/dev/build/whitestorm.js

**Comment by sasha240100** [comment]
@kaelhem may I close it?

**Comment by kaelhem** [comment]
Yes, I think you can.
Indeed, I was not able to make things working properly... It seems too early to integrate constraints. It's currently not documented and groups are not included in the physic layer. So... I must switch to another engine for now, but I will keep an eye on your work for the future !

**Comment by sasha240100** [comment]
@kaelhem tell us more about groups in the physics layer. As r11 is ready and I have no open priorities for next version - I can try implementing groups and write docs for constraints.
It will be nice if you add some links or examples so I can understand what I should do

**Comment by sasha240100** [comment]
@kaelhem Added both:
 - [Groups / Mask](https://whs-dev.surge.sh/examples/#physics/filtering)
 - [DOF Constraint](https://whs-dev.surge.sh/examples/#constraints/dof)

Those are available in **dev branch** already
