### ISSUE TITLE
Last commit on master breaks Examples/FPS

### ISSUE THREAD

**Issue by Rayjax** [WhitestormJS/whitestorm.js#112]
Pulled master, spawned a simple live-server, accessed examples/fps:
script.js:2180 Uncaught TypeError: Cannot read property 'UniformsUtils' of undefined
User and world spawn very far away and fall down.

git checkout HEAD^ -> works fine

###### Version:
 - [x] r11

###### Issue type:
 - [x] Bug

###### --- Desktop
   - [x] Chrome

**Comment by sasha240100** [comment]
@Rayjax That's a problem appeared in terrain plugin after updating three.js version from r79 to **r80**. I hope it will be solved in the nearest time.  It would be nice if you help us to solve it (make a pull request)
