### ISSUE TITLE
Which license do you use?

### ISSUE THREAD

**Issue by kennynaoh** [WhitestormJS/whitestorm.js#114]
Hello @sasha240100 ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question about license want to ask.
I found that the license you mentioned in [package.json](https://github.com/WhitestormJS/whitestorm.js/blob/dev/package.json#L30) is `CC`
Any detail about it.
Please take a look at [this](https://github.com/kennynaoh/cdnjs/blob/master/tools/license-list.json#L60).

I also found that you mentioned in [bower.json](https://github.com/WhitestormJS/whitestorm.js/blob/dev/bower.json#L16)
So you mean you use dual license, right?
If yes, please also mention the detail of `Apache` you use, what version?

Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8951

**Comment by sasha240100** [comment]
@kennynaoh It's CC-BY-NC-ND-4.0 now. The one in bower is just a typo.
Also: It's possible that we will update the license in the nearest time. I'll keep you in touch.
Thanks for hosting us!

**Comment by kennynaoh** [comment]
Thanks @sasha240100 ,
Another question is about the files needed to be grab on [npm](https://www.npmjs.com/package/whitestormjs).
I think the main file is `build/whitestorm.js`, right?
What about `build/whitestorm.light.js`? Is it necessary to add?
Please help me confirm that.
Thanks!

**Comment by sasha240100** [comment]
@kennynaoh Yes, add please both if you can. Developers should choose the one they use.

**Comment by kennynaoh** [comment]
Thanks @sasha240100

**Comment by kennynaoh** [comment]
Hello @sasha240100 ,
A question again~
I found that there are different naming scheme.
In the latest version `0.11.2`, both js files are minified.
But in old versions, the `whitestorm.js` are not minified.
Could you change the minified js file name to `whitestorm.min.js` in the latest version?
Or
Directly offer not minified js file, and we can minified it.
Thanks for your help!

**Comment by sasha240100** [comment]
@kennynoah There we have a problem, cause library uses webpack is too big. So in minified file wouldn't help in development without sourcemap. Since r11 (0.11.x) we provide only minified files for usage.

**Comment by kennynaoh** [comment]
Thanks @sasha240100 ,
So could you change the name to `whitestorm.min.js` in the latest version?
Thanks!

**Comment by sasha240100** [comment]
@kennynaoh I probably will in next version

**Comment by kennynaoh** [comment]
@sasha240100 
no problem

**Comment by sasha240100** [comment]
@kennynaoh So now it's MIT. Should i notify you when new release is ready?

**Comment by sasha240100** [comment]
@kennynaoh Hello again. I think now it's time to talk about CDN. I updated all infromation in https://github.com/cdnjs/cdnjs/issues/8951 to follow latest project details
