### ISSUE TITLE
Multiple post-processing renderTarget

### ISSUE THREAD

**Issue by typedef42** [WhitestormJS/whitestorm.js#117]
The goal is to provide a simple API that allow to compose rendering output from different RenderTargets and so PostProcessing instances.

This can be used to achieve effects like godrays, bloom, glow etc complex post processing effects.

**Comment by sasha240100** [comment]
@typedef42 Any updates on this issue?

**Comment by typedef42** [comment]
Nop sorry, I didn't had time to make real progress yet.

**Comment by sasha240100** [comment]
@typedef42 Point me to some problems or bugs that you've found, i'll try to reproduce them. If you don't have a time - assign this issue to somebody else or me.

**Comment by typedef42** [comment]
@sasha240100 Sorry, as I mentioned in private, some emergency prevent me to invest time on this right now. I'm coming back to finish it ASAP, with additional post processing examples ! :)

**Comment by sasha240100** [comment]
@typedef42 Was that fixed?
