### ISSUE TITLE
cff

### ISSUE THREAD

**Issue by typedef42** [WhitestormJS/whitestorm.js#118]
Describe your issue here.

###### Version:
 - [ ] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
?

**Comment by typedef42** [comment]
that's what happens when I forgot to lock my session from my kids... sorry. - to delete.

**Comment by sasha240100** [comment]
@typedef42 No problems:D
