### ISSUE TITLE
Move WHS.Skybox to a plugin.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#119]
Component should be made using [generator-whs-plugin](https://github.com/WhitestormJS/generator-whs-plugin) and configured with such values:
 - Type: **Component**
 - Name: **whs-component-skybox**
 - Babel: **yes**
 - Bower: **yes**
 - gh-pages (serve): **yes**
 - Component name in browser: **WHS.Skybox**

**Comment by electron0zero** [comment]
Fixed in this [commit](https://github.com/WhitestormJS/whitestorm.js/commit/3e24539cf0d568bbf04c094a530d328932cfd2a3)

**Comment by sasha240100** [comment]
@electron0zero @mrinalpande
1. Add docs/wiki/readme with usage guide
2. Have you published it to npm?

**Comment by electron0zero** [comment]
i am working  on examples, yet to publish examples on gh-pages and component on npm
