### ISSUE TITLE
What should happen when applying opacity less than 1 to a node with descendants?

### ISSUE THREAD

**Issue by trusktr** [WhitestormJS/whitestorm.js#120]
Hello Alex,

I'd like your opinion:

If we have a node in a 3D scene, and it has many descendants (a sub tree), what should happen when we apply opacity with a value less than `1` to it?

1. It, and all of it's children should become transparent, multiplying opacities down the scene graph.
1. It's content should become transparent but not that of its descendants.
1. Same as (1), but the whole object should be flattened into a plane.

The reason I want your opinion is because the new specs for CSS 3D (css-transforms) [state here](https://drafts.csswg.org/css-transforms/#grouping-property-values) that the answer is (3).

To see what I mean, view these two examples in Chrome 53 or higher:

- https://jsfiddle.net/trusktr/ymonmo70/16
- https://jsfiddle.net/trusktr/ymonmo70/17

The second example has opacity applied to the node that contains all the sub-nodes which compose the car. The opacity, according to spec, flattens the car into a plane (turns it into paper!).

I'm asking various 3D engine authors for opinions of what the correct or most expected behavior should be.

All the best,
~ Joe

**Comment by sasha240100** [comment]
@trusktr you apply opacity not to the node, but to the material. It means that transparent will be only the main object, but not it's children (I can be wrong, you may check)

It's better to look in three.js docs.

**Comment by trusktr** [comment]
True, which means opacity applies only to the object at a node, not to objects at child nodes. Would you agree that flattening is undesirable?

**Comment by sasha240100** [comment]
@trusktr sure
