### ISSUE TITLE
WHS.SliderConstraint doesn't work as expected.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#122]
[WHS.SliderConstraint](https://github.com/WhitestormJS/whitestorm.js/blob/dev/src/framework/physics/constraints/SliderConstraint.js) doesn't work as expected. Method `.setEuler()` is not in _btQuaternion_.

**Actual problem**

I tried to replace `.setEuler()` with [`.setEulerZYX()`](http://bulletphysics.org/Bullet/BulletFull/classbtQuaternion.html#a808b430136b4a8d1e7120134af14a1ff) but still no good result.  - No error, but blue box moves along (0, 1, 1) direction. Replacing XYZ doesn't help.

**Blue box should move along Z axis.** 

![](http://i.imgur.com/iBmeCI6.png)

**Part of the code where error occurs**

Line [930](https://github.com/WhitestormJS/whitestorm.js/blob/dev/src/framework/physics/worker.js#L930) and [943](https://github.com/WhitestormJS/whitestorm.js/blob/dev/src/framework/physics/worker.js#L943)

``` javascript
        transforma.setOrigin(_vec3_1);

        let rotation = transforma.getRotation();
>>      rotation.setEuler(details.axis.x, details.axis.y, details.axis.z);
        transforma.setRotation(rotation);
```

Some of other constraints use `.setEulerZYX()` already.
---

![image](https://cloud.githubusercontent.com/assets/7657429/19497063/0e153686-9593-11e6-85f3-57ee721c2ccd.png)
###### Version:
- [x] r12 (dev)
- [ ] r11
- [ ] r10
- [ ] r9
- [ ] r9 (dev)
- [ ] r8
- [ ] r7
###### Issue type:
- [x] Bug
- [ ] Proposal/Enhancement
- [ ] Question
---

<details> 
<summary>

 <b>Tested on: </b> </summary>

###### --- Desktop
- [x] Chrome
- [ ] Chrome Canary
- [ ] Chrome dev-channel
- [ ] Firefox
- [ ] Opera
- [ ] Microsoft IE
- [ ] Microsoft Edge
###### --- Android
- [ ] Chrome
- [ ] Firefox
- [ ] Opera
###### --- IOS
- [ ] Chrome
- [ ] Firefox
- [ ] Opera

</details>

**Comment by sasha240100** [comment]
@preco21 I assign you to this issue. Look what you can do.

**Comment by preco21** [comment]
Hmm sorry, I have no idea about that. As far as I know, if this problem is just rotation related issue, I assume [Quaternion](https://threejs.org/docs/api/math/Quaternion.html) rotation would fix this issue.

**Comment by sasha240100** [comment]
@preco21 check all possible ways

**Comment by sasha240100** [comment]
@preco21it is also possible to make a new build of ammo.js with `.setEuler()`

**Comment by sasha240100** [comment]
If someone is going to make a new port with `.setEuler()` in **btQuaternion**:
 - https://github.com/WhitestormJS/ammo.js/blob/master/ammo.idl#L53 - see this line in _ammo.idl_.
 - [WebIDL guide](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html)
 - It's **better to have linux**, because i had some troubles with building on windows. [See this](https://github.com/kripken/ammo.js/issues/136)

**Comment by sasha240100** [comment]
Updated ammo.js. Now works
