### ISSUE TITLE
Installation Obstacle (probably easy fix)

### ISSUE THREAD

**Issue by KieranTimberlake** [WhitestormJS/whitestorm.js#132]
Hey guys,

I'm trying to install and use whitestorm on an Ember application. I added the whs module using 'npm install' and get 'WHS' using browserify. When I attempt to create a world (the sample world from the tutorial), 75 errors are thrown. Everything seemingly runs smoothly until World.js attempts to add a camera. After adding the World, the screen goes black (as it should), but nothing exists inside the world.

Here's a picture of chrome's inspect:
![pic](https://cloud.githubusercontent.com/assets/4663097/20485313/f4372c7e-afc8-11e6-846a-686a5767c74a.png)

My code (not sure how to format correctly): 
`setWorld: function() {
const world = new WHS.World({
        autoresize: "window",
        rendering: {
          background: {
            color: 0x162129
          }
        },
        gravity: [0, -100, 0], // Physic gravity.
      });
    }`

 

whs version: 1.1.9
three version: 0.82.1

Issue Type: Maybe bug, maybe I'm being an idiot

**Comment by KieranTimberlake** [comment]
![image](https://cloud.githubusercontent.com/assets/4663097/20485525/f2353186-afc9-11e6-8815-bdea41e76f14.png)

**Comment by sasha240100** [comment]
@KieranTimberlake contact me in discord chat please

**Comment by sasha240100** [comment]
@KireanTimberlake https://discord.gg/vA5Xz
Username: alex2401
