### ISSUE TITLE
Grid component

### ISSUE THREAD

**Issue by thejmazz** [WhitestormJS/whitestorm.js#135]
Making my own `Grid` component which wraps [GridHelper](https://threejs.org/docs/#Reference/Extras.Helpers/GridHelper) (but more generally can be a component to make grids). This might even lead to making it use `Line` component too.

From the Three source, can see it uses a custom `BufferGeometry` and `LineBasicMaterial`, which calls the `LineSegments` constructor which calls `Line` constructor (and just sets `type` to `LineSegments`) and that `Line` looks to be what `WHS.Line` wraps. So, I think it would probably make sense for `Grid` to use that, rather than wrapping `GridHelper`.

I also wanted to have control over `position`, `rotation`, etc. So can do this by copy/pasting code from `MeshComponent` class and that works. However I still do not have

- [ ] ability to set `Grid` rotation from constructor
- [ ] ability to have `position`, `rotation`, etc w/o copy pasting code from `MeshComponent` class

Would be nice if there were some way to add these sorts of features to classes, maybe through (multiple) inheritance or composition. Composition could be something like `isRotatable`.

So, instead of copy/pasting code, would like to extend `MeshComponent` instead. However when doing this I get:

```
Uncaught TypeError: Super expression must either be null or a function, not object
```

```javascript
// Grid.js
const { Component, MeshComponent } = WHS

class Grid extends Component {
  static defaults = {
    size: 5,
    step: 10,
    colorCenterLine: 0x888888,
    colorGrid: 0x888888,
    rotation: { x:0, y: 0, z: 0 }
  }

  constructor (params = {}) {
    // alternatives?
    params = Object.assign({}, params, Grid.defaults)

    super(params, MeshComponent.defaults, MeshComponent.instructions)

    const { size, step, colorCenterLine, colorGrid } = params

    this.native = new THREE.GridHelper(size, step, colorCenterLine, colorGrid)
  }

  // Taken from MeshComponent source
  get rotation() {
    return this._native.rotation;
  }

  set rotation(euler) {
    this._native.rotation.copy(euler);
    return this._native.rotation;
  }
}

export default Grid

export const xzGrid = new Grid()

export const xyGrid = new Grid()
xyGrid.rotation.x = - Math.PI / 2
// how to do:
// new Grid({ rotation: { x: - Math.PI / 2, y: 0, z: 0 } })
// or even: (would probably require nested Object.assign's)
// new Grid({ rotation: { x: - Math.PI / 2 } }) 
```

###### Version:
 - [x] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [x] Question

**Comment by sasha240100** [comment]
@thejmazz Why not using @MeshComponent decorator. Open any component in src/framework/components/meshes to see how it works.
