### ISSUE TITLE
Mouse Pan Broken

### ISSUE THREAD

**Issue by thejmazz** [WhitestormJS/whitestorm.js#136]
Mouse pan broken due to thunk methods not being invoked. I have fix, will make PR soon. 

For example, diff on `panLeft`:

```
-    const panLeft = () => {
+    const panLeft = (() => {
       const v = new Vector3();

-      return function panLeft(distance, objectMatrix) {
+      return (distance, objectMatrix) => {
         v.setFromMatrixColumn(objectMatrix, 0); // get X column of objectMatrix
         v.multiplyScalar(-distance);

         panOffset.add(v);

       };
-    };
+    })();
```

###### Version:
 - [x] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
Pan is now fixed.
