### ISSUE TITLE
Geometry options consistency

### ISSUE THREAD

**Issue by thejmazz** [WhitestormJS/whitestorm.js#138]
Right now for example `WHS.Plane` takes

```
geometry: {
  width: 10, // Number
  height: 10, // Number
  wSegments: 32, // Number
  hSegments: 32 // Number
}
```

and `WHS.Sphere` takes

```
geometry: {
  radius: 1, // Number.
  widthSegments: 8, // Number
  heightSegments: 6 // Number
}
```

Whether it is `wSegments` or `widthSegments`, we should just be consistent.

**Comment by sasha240100** [comment]
@thejmazz Already fixed in [beta](https://github.com/WhitestormJS/whitestorm.js/tree/beta) branch.
