### ISSUE TITLE
Preload for projects/examples

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#14]
We will make a **preload** function or api for filling screen with animated gif or loading state while project is loading. This is just for **`beauty`**.

For example with this:

<img src="https://raw.githubusercontent.com/WhitestormJS/whitestorm.js/master/development/art/logo/animation_gif/ease.gif" width="100" height="100">

But you can choose another variant like:
 - http://github.hubspot.com/pace/docs/welcome/
 - https://ihatetomatoes.net/create-custom-preloading-screen/
 - http://bradsknutson.com/blog/display-loading-image-while-page-loads/

**Comment by jackdalton** [comment]
Closed by b9e01e4.
