### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'mapSize' of undefined

### ISSUE THREAD

**Issue by tiaod** [WhitestormJS/whitestorm.js#140]
![image](https://cloud.githubusercontent.com/assets/7500825/21499571/17a73e36-cc72-11e6-84d7-b6472e50483a.png)
This shows up after I add a HemisphereLight
```javascript
new WHS.HemisphereLight({
  light: {
    skyColor: 0xff0000,
    groundColor: 0x0000ff,
    intensity: 0.2
  }
}).addTo(world);
```
###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

</details>

**Comment by sasha240100** [comment]
@tiaod Can you go to that line (VM...:21) and show me what it shows?

**Comment by tiaod** [comment]
![image](https://cloud.githubusercontent.com/assets/7500825/21499869/9e83f0f0-cc74-11e6-8e18-a9a94c45c9fd.png)
Sorry, my english isn't good.
It shows up when I add the flowing code:
```javascript
new WHS.HemisphereLight({
  light: {
    skyColor: 0xff0000,
    groundColor: 0x0000ff,
    intensity: 0.2
  }
}).addTo(world);
```

But if I wrap the `HemisphereLight` using `WHS.Element`, the error has disappear:
```
var hemiLight = new THREE.HemisphereLight( 0xffffff, 0xffffff, 0.6 );
hemiLight.color.setHSL( 0.6, 1, 0.6 );
hemiLight.groundColor.setHSL( 0.095, 1, 0.75 );
hemiLight.position.set( 0, 500, 0 );
var element = new WHS.Element(
  hemiLight,
  [WHS.LightComponent]
)
element.addTo(world)
```
![image](https://cloud.githubusercontent.com/assets/7500825/21499983/8c3c6d9a-cc75-11e6-8d44-02d859f7b670.png)

**Comment by sasha240100** [comment]
@tiaod It seems like it is API regression after update to newer three.js version on our side. 
For now I'd recommend to use it with `WHS.Element` as you do it. I am working now in **beta** branch and will fix this issue once i get all my examples working in that branch.

**Comment by sasha240100** [comment]
@tiaod I made an [announcement about the beta](https://whsjs.readme.io/v1.2/blog/v2-beta). If you want to participate in development - ask me in [discord channel](https://discordapp.com/invite/frNetGE)

**Comment by sasha240100** [comment]
@tiaod Should be fixed now
