### ISSUE TITLE
world.render = false; //Not working

### ISSUE THREAD

**Issue by tiaod** [WhitestormJS/whitestorm.js#141]
![image](https://cloud.githubusercontent.com/assets/7500825/21539557/f0501868-cde2-11e6-9aa3-064ac843154f.png)
it still rendering my scene after I set `world.render = false`
![image](https://cloud.githubusercontent.com/assets/7500825/21539578/299b8d50-cde3-11e6-986c-c33026bd86ca.png)

###### Version:
 - [ ] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [x] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@tiaod Seems like it is regression in last whsjs (after moving rendering part away from World component). I'll fix that in beta, but idk how long to wait until beta become stable.

**Comment by tiaod** [comment]
Any other way i could do to pause render? I think it's a very important feature for SPA.

**Comment by sasha240100** [comment]
@tiaod How do you use whitestormjs, with webpack or just with a script tag?

**Comment by tiaod** [comment]
With a script tag. I had try to import it with webpack however it throw an error. So I just use whs with a script tag.

**Comment by tiaod** [comment]
@sasha240100 Should I use webpack import instead of script tag?

**Comment by sasha240100** [comment]
@tiaod Just asked. You may try version from master branch. I remember that I had that .render working some time ago.

It used to work till we moved rendering away from WHS.World

**Comment by sasha240100** [comment]
@tiaod See my PR #173 if that fits. And then i merge it
