### ISSUE TITLE
Default Playground not running

### ISSUE THREAD

**Issue by jywarren** [WhitestormJS/whitestorm.js#142]
I went to the playground link on the README (http://playground.whsjs.io/):

```
jquery.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
loadExample @ core.js:24
core @ core.js:35
(anonymous) @ core.js:35
core.js:33 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'whs' exceeded the quota.
    at setVersion (http://playground.whsjs.io/js/core.js:33:48)
    at HTMLDocument.<anonymous> (http://playground.whsjs.io/js/core.js:6:1)
    at j (http://playground.whsjs.io/js/jquery.min.js:2:27136)
    at Object.fireWith [as resolveWith] (http://playground.whsjs.io/js/jquery.min.js:2:27949)
    at Function.ready (http://playground.whsjs.io/js/jquery.min.js:2:29783)
    at HTMLDocument.K (http://playground.whsjs.io/js/jquery.min.js:2:30128)
setVersion @ core.js:33
(anonymous) @ core.js:6
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
K @ jquery.min.js:2
VM502:2 Uncaught ReferenceError: WHS is not defined
    at <anonymous>:2:19
    at core.js:17
```

But the scene didn't render -- looks like an amazing library, thanks!

###### Version:
 - [ ] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### --- Desktop

   - [x] Chrome (chromeOs)
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@jywarren Thanks! Playground is unstable right now and can have a lot of bugs. (Sorry for that)

That's because now we left whs v1 and everything related to make v2 (we refactored a lot of api in beta already) https://whsjs.readme.io/blog/v2-beta

**Comment by sasha240100** [comment]
@jywarren we'll fix up playground after releasing Whitestormjs 2

**Comment by jywarren** [comment]
Awesome -- excited! Thanks for the fast reply!

**Comment by electron0zero** [comment]
@jywarren moved this issue to [playground repo](https://github.com/WhitestormJS/playground/issues/5)
and mentioned a quick workaround until we fix it.
