### ISSUE TITLE
Adding physics is hard - other engines

### ISSUE THREAD

**Issue by Maksims** [WhitestormJS/whitestorm.js#144]
Readme states:
> Other frameworks: To make your app run with physics you need to make a second world with same 3d objects and apply their transform (position & rotation) to your rendered scene objects (THREE.Scene for example) in every frame.

In PlayCanvas using physics does not require to create another world. As there is physics component system: collision component and rigidbody component to describe physics for entities. No need to create another scene and do any syncing, everything handled automatically.

In BabylonJS I believe this is the same - handled automatically.

**Comment by jackdalton** [comment]
The text you quoted references the fact that other frameworks require more work to set up physics. It does not state that *all* other frameworks require more work, only "other frameworks."

**Comment by jackdalton** [comment]
@Maksims if you'd like to alter the text of the README file, open a PR.
