### ISSUE TITLE
DEMO gh-pages broken!!!

### ISSUE THREAD

**Issue by 7dir** [WhitestormJS/whitestorm.js#146]
Describe your issue here.

###### Version:
 - [ ] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
![](http://rs94.pbsrc.com/albums/l92/Ruas_2006/Caturday/Sad_Kitten_Is_Sad.jpg~c200)

**Comment by sasha240100** [comment]
@7dir Fixed some examples (from beta branch)
