### ISSUE TITLE
How to add the physics module with Webpack?

### ISSUE THREAD

**Issue by kahogeoff** [WhitestormJS/whitestorm.js#153]
I'm using the latest version of this framework, and try to add physics with `physics-module-ammonext`.

However, after looking for any documents on the Internet, I still have no idea how to adding the physics module on it with Webpack.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [x] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@kahogeoff Simply add a `import * as PHYSICS from 'physics-module-ammonext'` and that's it. I think I should do a repo to show it. **(It's not hard to do. Just remember that physics is simply a module and you should use it like any other module:))**

**Comment by kahogeoff** [comment]
Thanks for your solution.
But I got another problem now:
I'm using the [whitestorm-app-boilerplate](https://github.com/WhitestormJS/whitestorm-app-boilerplate). After I added
`import * as PHYSICS from 'physics-module-ammonext'` 
this line on the `app.js`, it show up the [following errors](https://gist.github.com/kahogeoff/46075efe98da3319b3ab48648acc7d77)

**Comment by sasha240100** [comment]
@kahogeoff You may need to setup appropriate babel presets and modules. It seems you missed some of them. I'll check more when at home
