### ISSUE TITLE
Add AreaLight

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#155]
`AreaLight` should be added to _src/components/lights_ as a part of light components system. 

`AreaLight` documentation: https://threejs.org/docs/index.html#Reference/Lights/RectAreaLight

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
PR #160, what do you think?
