### ISSUE TITLE
Playground is down

### ISSUE THREAD

**Issue by jlieb10** [WhitestormJS/whitestorm.js#164]
Can't use the playground in latest version of Chrome (tried standard and incognito windows, OSX user). Console errors attached.

<img width="721" alt="screen shot 2017-03-07 at 5 30 20 pm" src="https://cloud.githubusercontent.com/assets/3300789/23669398/e44e26b4-035b-11e7-9a4f-f9bd3d2cbdc2.png">

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@jlieb10 playground is deprecated. Use codepen instead
