### ISSUE TITLE
Move defaults from LightComponent to each light component

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#166]
This is more related to code clearness than to a bug, but has a place to be. I suggest moving `light` default out from `LightComponent`.

![image](https://cloud.githubusercontent.com/assets/7657429/23702231/0d213e26-0403-11e7-8d39-6f2f647c4dc3.png)

This will result in a better structure cause there will be only light-specific parameters per each light type.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
Merge to beta?
