### ISSUE TITLE
Update CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#168]
Some use cases of [`CONTRIBUTING.md`](https://github.com/WhitestormJS/whitestorm.js/blob/beta/.github/CONTRIBUTING.md) file are deprecated since of refactoring changes in V2 and we should update them:

- [x] [**CLI**](https://github.com/WhitestormJS/whitestorm.js/blob/beta/.github/CONTRIBUTING.md#cli)
  - [x] Fix commands, add new ones.
  - [x] Force the use of **npm commands**
- [x] [**Commit names**](https://github.com/WhitestormJS/whitestorm.js/blob/beta/.github/CONTRIBUTING.md#commiting)
  - [x] New rule: no dot after short codes
  - Use of **WIP** is now undesirable.
- [x] [**Changelog**](https://github.com/WhitestormJS/whitestorm.js/blob/beta/.github/CONTRIBUTING.md#-adding-changes-to-changelogmd) - is now deprecated. Use [github releases](https://github.com/WhitestormJS/whitestorm.js/releases)

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
What are the appropriate npm commands to do dev. when I attempted using npm I faced some difficulties... I'm using `gulp dev` for dev. what should it be?

**Comment by hirako2000** [comment]
Are you able to complete this task @sasha240100 ? I adjusted most part, but still need to
- Clarify what is the recommend way to dev locally (gulp or webpack command)
- Remove the changelog part if it's not relevant any more.

**Comment by sasha240100** [comment]
@hirako2000 I will. I also plan to add: 
- [ ] more detailed description of how to make PRs
