### ISSUE TITLE
Memory leak on webgl context disposal

### ISSUE THREAD

**Issue by Jule-** [WhitestormJS/whitestorm.js#174]
Hi again,

I think I have found a memory leak issue in WHS when I want to unload all WHS.App in a running page.

I have done some memory tests and it appear that Chrome Dev Tools show detached DOM tree leaks:

![image](https://cloud.githubusercontent.com/assets/9716736/23670145/177f4fc6-0367-11e7-971d-6e8635950666.png)

- Snapshot 1: before initializing the scene (before `new WHS.App()`)
- Snapshot 2: after initializing the scene
- Snapshot 3: after releasing the gl context and all WHS variables.

For what I understand you are making references to DOM Div and/or Canvas inside WHS context or sub-context and never releasing them. I have not tried with non minified WHS so the source localisation is pretty hard to figure.

You can test this on my test repository here: https://github.com/Jule-/AureliaWHS.
```shell
> cd AureliaWHS
> yarn
> au run --watch
```
(if you don't use `yarn`, `npm install` should do the trick, but imho you should take a look to this tool if you want to make some more deterministic dev environment 😉)

- Then navigate to: http://localhost:9000/without-aurelia.html
- Take a heap snapshot in Chrome Dev Tools
- Click `Initialize` button
- Take a new heap snapshot
- Click `Clean (full => ok)` button
- Take a new heap snapshot
- Ensure options:
![image](https://cloud.githubusercontent.com/assets/9716736/23716436/974e67b8-0430-11e7-9402-c694de47cc40.png)

**Bonus:** If you are curious and hit `Clean (light => throw)` button you will see another strange error in the console linked to WHS.

**Bonus:** You can check that this test case implemented with pure `THREE` scene is working good at: http://localhost:9000/without-aurelia-three.html

Enjoy!

------

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@Jule- Can i talk with you in discord?
