### ISSUE TITLE
Move modules from repos to /modules/

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#184]
As we now use `/modules/` folder to keep modules. We should move there some other modules that we keep updating:
 - [x] [whs-module-statsjs](https://github.com/WhitestormJS/whs-module-statsjs) https://github.com/WhitestormJS/whitestorm.js/pull/193/commits/4a3bf968a2abb18ab5e3306850d0f31ba8ec45eb 
 - [x] [whs-module-dat.gui](https://github.com/WhitestormJS/whs-module-dat.gui) https://github.com/WhitestormJS/whitestorm.js/pull/193/commits/a76c7c587a09e4ab5d51d3af106a91d88a0b1586

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by thejmazz** [comment]
how to still keep them separately versioned?

**Comment by sasha240100** [comment]
@thejmazz It will be. npm packages will be. Just them will be moved to this repo
