### ISSUE TITLE
[Bug] Shader doesn't compile on FPS example (Linux/Chrome)

### ISSUE THREAD

**Issue by jackdalton** [WhitestormJS/whitestorm.js#19]
The FPS example is broken on several Linux distributions. [Attached is a console log.
](https://github.com/sasha240100/WhitestormJS/files/69100/fps-example-err.txt)

[Zipped recording](https://github.com/sasha240100/WhitestormJS/files/69124/fpserr.zip)

**Comment by jackdalton** [comment]
Chrome v47.0.2526.106 (Official Build) (64-bit)

**Comment by jackdalton** [comment]
Kubuntu 15.10 x64.

**Comment by jackdalton** [comment]
It was a WebGL compatibility issue with the operating system. There's nothing we can do.

**Comment by jackdalton** [comment]
Same happens with Arch Linux x64.

Specific error message:

`error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later`

**Comment by jackdalton** [comment]
Related to mrdoob/three.js#6115.

**Comment by jackdalton** [comment]
Happens on http://chandlerprall.github.io/Physijs/examples/jenga.html as well.

**Comment by jackdalton** [comment]
Confirmed by another user [here](https://www.reddit.com/r/javascript/comments/3ze9s4/cannonjs_impressive_physics_engine_written_in/cymjfab).

**Comment by jackdalton** [comment]
mrdoob/three.js#6929

**Comment by jackdalton** [comment]
[spite's suggestion](https://github.com/mrdoob/three.js/issues/6929#issuecomment-127413599) yielded nothing, composer size is set [here](https://github.com/WhitestormJS/whitestorm.js/blob/master/src/whitestorm.js#L185).

**Comment by Mugen87** [comment]
See [WebGL shader fails to initialize](https://code.google.com/p/chromium/issues/detail?id=550487). The bug will be fixed with Chrome 49.

The dev-build of Chrome already contains the fix. All my test cases work properly.

**Comment by Mugen87** [comment]
Besides, the error doesn't occur with the latest `dev` version of three.js.

**Comment by sasha240100** [comment]
@Mugen87 Thanks! Is that version stable now?

**Comment by Mugen87** [comment]
@sasha240100 No, it's just the latest build of the `dev` branch. I don't recommend to use it in production. This [commit](https://github.com/mrdoob/three.js/commit/8ecba28065584fbefe7ba006c2127947eb76f8df) fixes the issue. If you need a hotfix, you can implement it in a custom build of three.js.

**Comment by sasha240100** [comment]
@Mugen87 Will [this](https://www.google.com/chrome/browser/desktop/index.html?platform=linux&extra=devchannel) one support this fix?*(dev channel)*

**Comment by Mugen87** [comment]
Yeah, i use this version of Chrome on my Ubuntu.

**Comment by jackdalton** [comment]
@Mugen87 Thanks for taking the time to help us out with this, not being able to see some of our demos has been driving me crazy. I grabbed [`google-chrome-dev`](https://aur.archlinux.org/packages/google-chrome-dev) out of the AUR, and everything works. I've just been using [`google-chrome-beta`](https://aur.archlinux.org/packages/google-chrome-beta), I never thought to test with Chrome's dev build.
