### ISSUE TITLE
this.native undefined in getter for copied attributes in MeshComponent

### ISSUE THREAD

**Issue by thejmazz** [WhitestormJS/whitestorm.js#190]
If you have the following code as a module for a `MeshComponent` (e.g. `Sphere`):

```javascript
class MyModule {
  integrate (self) {
    console.log(this.position) // cannot read property 'position' of undefined
    // undefined comes from this.native in getter
  }
}
```

Then when this is called in `ModuleSystem.applyModule`:

```javascript
if (module.integrate) module.integrate.bind(this)(module);
```

Then it will invoke the `position` getter, which is defined by 

```javascript
export function copy(...map) {
  return {
    map,
    getter(name) {
      return function () {
        // this.native is undefined here
        return this.native[name];
      };
    },
    setter(name) {
      return function (value) {
        this.native[name].copy(value);
      };
    },
    configurable: true,
    enumerable: true
  };
}
```

in `core/prototype/attributes.js`, and decorates `MeshComponent`:

```javascript
@attributes(
  copy('position', 'rotation', 'quaternion', 'scale'),
  mirror('material', 'geometry')
)
class MeshComponent extends Component {
  ...
}
````

![image](https://cloud.githubusercontent.com/assets/1270998/23834635/2ec1dcea-0730-11e7-9766-dda02ddbcce3.png)

![image](https://cloud.githubusercontent.com/assets/1270998/23834640/4cec98fe-0730-11e7-87fe-423ccf7fd32c.png)

**Comment by sasha240100** [comment]
@thejmazz `integrate()` is called before build. You'll​ need to do that in a `mesh` bridge. I will give you a link of how it is on AudioModule soon

**Comment by thejmazz** [comment]
Ahh. Yes, I just noticed that `this.native` gets set from result of `build`

**Comment by sasha240100** [comment]
https://github.com/WhitestormJS/whitestorm.js/commit/e595bf9048219eb48a3a37355dac164416f2d2d4

**Comment by sasha240100** [comment]
See this

**Comment by thejmazz** [comment]
So then is integrate in a module meant **only for creating new properties on the component** ?

**Comment by sasha240100** [comment]
@thejmazz, yes, mostly) you can also modify things in `this`(component) scope, but not `native`. Can I close this?

**Comment by thejmazz** [comment]
are these lifecycle patterns and what can/cannot be done in manager, integrate, bridges documented anywhere? (this [post](https://hackernoon.com/migrating-to-whitestormjs-v2-beta-module-system-2eeaeda08a80#.h3lftu352) not enough)

If not, maybe rename this issue to something along the lines of "document core class APIs lifecycle and method capabilities" and leave it open. 

I'm currently doing my best to understand how these core classes behave.

I also wonder if it you would then be possible to throw an error message if user attempts to get a property before build which can only be available after build, instead of an uncaught TypeError

**Comment by hirako2000** [comment]
I also found the doc a bit unclear, I called out the ordering **Life Cycle* for modules, we need to improve the doc yes, to be more precise about the Life Cycle of Modules relative to the Component cycle.
https://whsjs.readme.io/docs/modules-1

**Comment by sasha240100** [comment]
@thejmazz @hirako2000 Seems like we need to define how component is executed. I'd like to have an image that explains it with arrows

**Comment by sasha240100** [comment]
@thejmazz You can leave a suggestion in docs
