### ISSUE TITLE
Examples page to follow responsive web design

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#194]
The examples page layout is good but does not work well on small screen like mobiles, the side bar occupies most of the screen, see screenshot.

- Hide side bar content if screen is below a certain size
- Make selected example name show at the top for small screen
- Add toggle showing on small screen to display the full list
- Hide toggle when another example item is clicked.

![image](https://cloud.githubusercontent.com/assets/1500712/23848182/93da1150-0808-11e7-9ae8-ee9426763f89.png)

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@hirako2000 Looking forward to see this implemented^^

**Comment by sasha240100** [comment]
@hirako2000 Anything i can do? (help with smth)

**Comment by sasha240100** [comment]
**New design**

![image](https://cloud.githubusercontent.com/assets/7657429/24156013/0e818a04-0e5e-11e7-860e-bde7ae78d109.png)

![image](https://cloud.githubusercontent.com/assets/7657429/24156041/1fdc1f6c-0e5e-11e7-9f49-e8d5e2c5f541.png)

**Comment by sasha240100** [comment]
Test of adaptive design on **Nexus 5X**

**UI**

- **Swipe from left side.** Triggers sidebar.

![image](https://cloud.githubusercontent.com/assets/7657429/24165585/736c2fe4-0e79-11e7-8a4b-0c009fc33bbe.png)

![image](https://cloud.githubusercontent.com/assets/7657429/24165590/76c6ba56-0e79-11e7-8375-effdebfc7d59.png)
