### ISSUE TITLE
Add Semantic UI to examples

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#195]
I do like semantic UI and I think we can use it in examples. **Some ideas of where it can be used:**

- [x] **Preloading example page.** First loading of whs can take some time, and it will be nice to have a preloader/spinner.
![image](https://cloud.githubusercontent.com/assets/7657429/23851195/353cad6e-07eb-11e7-85e0-c4931070c0e7.png)

- [x] **Sidebar.** Just to handle examples.
![image](https://cloud.githubusercontent.com/assets/7657429/23851327/c63b875e-07eb-11e7-9872-dfbdadf6880b.png)
> Should be responsive!! See #194

- [x] **Buttons.** Some examples may have buttons that take actions.
![image](https://cloud.githubusercontent.com/assets/7657429/23851228/66a3e714-07eb-11e7-8d86-57f699f5f7cc.png)

- [x] **Search.** I hope about implementing a filter in examples panel
![image](https://cloud.githubusercontent.com/assets/7657429/23851246/84b49fe6-07eb-11e7-8114-8b36fa56808b.png)

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
the semantic-ui item appears in the examples page (and of course nothing to show) we should add it to the folders to ignore from display.

**Comment by sasha240100** [comment]
@hirako2000 I will soon add it to current design (At least loader)
