### ISSUE TITLE
Revisit Line component

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#217]
The [`Line`](https://github.com/WhitestormJS/whitestorm.js/blob/beta/src/components/meshes/Line.js) component has no test. no example.
Let's revisit this component. Fix it if necessary, support handful function, and create an example to illustrate how it works.

- [x] add start/end params to Line
- [x] add example to show how line work with two vertices 
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
curve is mandatory. Line requires a curve, contrary to what the doc says.
Should we just fix the doc?

**Comment by sasha240100** [comment]
@hirako2000 Fix the doc. But I think we can completely rewrite Line coponent as it is not a Line at all (now)

**Comment by sasha240100** [comment]
@hirako2000 What's the progress?

**Comment by hirako2000** [comment]
fixed styles (finally)
