### ISSUE TITLE
Change naming style from whitestorm.js and whitestorm.compact.js to whitestorm-full.js and whitestorm-compact.js?

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#220]
Pointed out recently, the compact vs full can be somewhere unclear without reading the doc or asking.
Would it make sense to rename the bundled flavors? I think it's pretty common to have `compact` or `light` appended, while keeping the full, without any suffix. Discuss.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [x] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@hirako2000 how about renaming into `whitestorm.core.js`?

**Comment by thejmazz** [comment]
I like using `.` instead of `-`

**Comment by Nodewarrior** [comment]
How about having whitestorm.mini.js? and keep the whitestorm.js as it is?

**Comment by sasha240100** [comment]
@Nodewarrior I think having just a compressed version is enough as it's not such a big. For other - use webpack + sources

**Comment by hirako2000** [comment]
We close? @Nodewarrior , .**min.js** is sort of _reserved_ as it  indicates minified file.

**Comment by sasha240100** [comment]
@hirako2000 I think we can close it, yes

**Comment by Nodewarrior** [comment]
Yeah, gotcha!
