### ISSUE TITLE
Codepen doesn't work

### ISSUE THREAD

**Issue by Viltaria** [WhitestormJS/whitestorm.js#236]
Codepen is broken
http://codepen.io/sasha240100/pen/wgEXwN 
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@Viltaria Thanks. Updated those link to use [`v2.0.0-beta.8` version](https://cdnjs.cloudflare.com/ajax/libs/whitestorm.js/2.0.0-beta.8/whitestorm.js) (Current latest)
