### ISSUE TITLE
[Design] #blocker div looks primitive

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#24]
Blocker div haven't changed since we made fps example. I think you may need to change design (css)
For example i like example [something like this](https://www.google.com.ua/search?q=splash+screen&biw=1422&bih=731&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjRxrbGuZLKAhVHk3IKHaCwC6MQ_AUIBigB#tbm=isch&tbs=rimg%3ACSOclWhlm7zsIjgwhGBZBYI74Ulw8EDD_1Q-CTp2qwYZVTaO4RNuHSZ7LLjo9kp10TUtqvQofDxRYf_1K8AamM9j8qfyoSCTCEYFkFgjvhEX_1mghofo1hoKhIJSXDwQMP9D4IROGLavD-nyksqEglOnarBhlVNoxE3v-PB2pJAtSoSCbhE24dJnssuEbiYVBReAQ_1pKhIJOj2SnXRNS2oRydP46weiHFcqEgm9Ch8PFFh_18hHIqSF5rvgqEioSCbwBqYz2Pyp_1EdHcy9HATjYP&q=splash%20screen%20game)

![now](https://cloud.githubusercontent.com/assets/7657429/12112611/5a9c1652-b3a6-11e5-89a1-9d919143a125.png)

Examples of good design (my choice :+1: :smile: ):

![First example](http://owrgames.com/dingleberry/wp-content/uploads/2015/05/Destint-Splash-screen-2.jpg)

![Second example](http://schmoesknow.com/wp-content/uploads/2014/09/1-Intro-Image.jpg)

![Third example](http://cdn2.expertreviews.co.uk/sites/expertreviews/files/styles/article_main_wide_image/public/6/29//destiny1.jpg?itok=ugg7g0hX)

![Fourth example](http://img.photobucket.com/albums/v221/HaZarD_SFD/Crysis3MPOpenBeta2013-02-0108-44-37-32_zps0a294113.jpg)

![Fifth example](https://d13yacurqjgara.cloudfront.net/users/45014/screenshots/864718/lumio_splashscreen_800x600.jpg)

![Sixth example](https://i.ytimg.com/vi/4c6u60fS-Ho/maxresdefault.jpg)

![Eighth](http://victordima.net/wp-content/uploads/2014/04/Official-Logo-The-Crew-Game-from-Ubisoft1.jpg)

![Nineth](http://static2.cdn.ubi.com/ncsa/watchdogs/wallpapers/wd_fox_wallpapers_desktop1920X1080.jpg)

![Tenth](http://nerdreactor.com/wp-content/uploads/2014/11/farcry-logo-wallpaper.png)

**Comment by jackdalton** [comment]
Great idea, I'm on it.

**Comment by jackdalton** [comment]
Huh, thought 8caad8e would close this. Thanks GitHub.

**Comment by sasha240100** [comment]
@jackdalton We don't need just an image. (Reason: too primitive.). We need a splash screen. This fps example later will be a shooter game(for example). So, please make a start screen that introduce user how to use this game (we need those text that describes controls. You can change this text, but it must describe controls.)
I said i like only design from those images (colors, style). It shouldn't be an image.
Okay, some tips for you, *follow them** and everything will be ok:
 - It shouldn't be jsut an image.
 - Blocker is a splash screen or menu for our game (fps example.)
 - Blocker should contain: "How to use" text (controls), engine logo (small, at the bottom, right corner), some other links (it can be a site or our [blog](http://whitestormjs.xyz/blog/first-post/))
 - Don't copy everything. It is your freedom. Suggest your design. It shouldn't look like engine example, it should look like a game. ...made with our engine.
 - It can be a page describing this fps example. Say that it is an island for example.
 - Some examples: 
  - http://www.ro.me/ (look at start screen)
  - http://gorescript.com/play/
  - http://hellorun.helloenjoy.com/
  - http://www.insidious-movie.net/entertheroom/

**Comment by jackdalton** [comment]
Got it.

**Comment by jackdalton** [comment]
Draft:

![draft image](https://cloud.githubusercontent.com/assets/10249860/12702706/0dac809c-c7ed-11e5-9a8b-512a9d64e7b1.png)

**Comment by sasha240100** [comment]
![image](https://cloud.githubusercontent.com/assets/7657429/14158429/aec19340-f6d8-11e5-93c3-3db5d452bbb2.png)
 * Fix margin between gif and text.
 * When pressing links (github, twitter) - it opens in a new tab, and nothing happens on page (#blocker don't hide)
 * **Why do you put whitestorm.js logo everywhere?** Fill this place with something another.

![image](https://cloud.githubusercontent.com/assets/7657429/14158521/2732ad78-f6d9-11e5-99d6-84711160ffa3.png)

* Loading logo is too big.

**Comment by sasha240100** [comment]
@t4r0 Made some changes. Now all is okay. But i suggest to make 1 more gif for mouse (like WASD). Can you make such? (After that i will close this issue.)
