### ISSUE TITLE
 Conveyor system

### ISSUE THREAD

**Issue by rahuldeo2047** [WhitestormJS/whitestorm.js#243]
How to design conveyors using this whitestorm?
contact motion etc
Let me know how can I contribute for the mentioned system dev.

###### Version:
 - [x] master

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [x] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [x] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [x] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
can you elaborate @rahuldeo2047 ? some example to see what's a conveyor? and what the system should do?

**Comment by rahuldeo2047** [comment]
Thank you for the response. :D 

An example only : https://www.youtube.com/watch?v=gVToWuG2QIA
Real conveyors : 
https://www.youtube.com/watch?v=Fd_zFi3W8q0
https://www.youtube.com/watch?v=d9o6JKfFwjc

Simplest approach:
If a box (white cuboid in image) having 'contact surface velocity' where any rigid body touches can get that velocity.
The velocity can change any time and body already in contact must get that velocity updated as well.

![screenshot from 2017-05-05 12-51-10](https://cloud.githubusercontent.com/assets/22162095/25736791/b7d31216-3191-11e7-8a89-fbf0259ab067.png)

I hope it clears all doubt.

**Comment by sasha240100** [comment]
@rahuldeo2047 The most clear way to do it (as on video) for me is to use **[hinge constraints](https://whs-dev.surge.sh/examples/?constraints/hinge)** between boxes (like it is on [your video](https://www.youtube.com/watch?v=gVToWuG2QIA)). And apply an angular velocity to result object (or something like this).

**But... From the point of optimization...**
I'd better make it so:
 1) A simple mesh with animation (long box in physics **[like on your screenshot, it's white]**)
 2) Make script that will check for contacts with other objects).
 3) Apply a one-direction velocity to all objects that collide with conveyor

**Comment by rahuldeo2047** [comment]
Any example for optimization point 1 and 2?
Thank you

**Comment by sasha240100** [comment]
@rahuldeo2047 

- [Physics world](https://github.com/WhitestormJS/physics-module-ammonext#new-physicsworldmodule)
- [Physics box](https://github.com/WhitestormJS/physics-module-ammonext/blob/master/README.md#new-physicsboxmodule)
- [Collision event](https://github.com/WhitestormJS/physics-module-ammonext/blob/master/README.md#collision)
- [Hinge constraint](https://github.com/WhitestormJS/whitestorm.js/blob/beta/examples/constraints/hinge/script.js#L79)

This should be enough for what you need. Note that for **physics** you should use [physics module](https://github.com/WhitestormJS/physics-module-ammonext).

If you need my help - contact me in [discord chat](https://discordapp.com/invite/frNetGE)

**Comment by rahuldeo2047** [comment]
Could not make it to work

https://github.com/rahuldeo2047/whitestorm-conveyor-belt-physics/blob/master/explore-whitestormjs.js#L117
I think I am missing something very basic.

---

Please let me know I'll move to discord from here if I should be there.

---
Secondly not to focus now : https://github.com/rahuldeo2047/whitestorm-conveyor-belt-physics/blob/master/explore-whitestormjs.js#L149 might need some documentation read.

**Comment by sasha240100** [comment]
A Vector3 object should be passed into applyCentralImpulse

**Comment by rahuldeo2047** [comment]
Still doesn't work
https://github.com/rahuldeo2047/whitestormjs-conveyor-belt-physics/blob/master/explore-whitestormjs.js#L121

---

But this works
https://github.com/rahuldeo2047/whitestormjs-conveyor-belt-physics/blob/master/explore-whitestormjs.js#L152

---

It seems the 'collision' method is not being called.
Any doc to study ? What can be the issues ?

**Comment by hirako2000** [comment]
Let's discuss in discord @rahuldeo2047

**Comment by rahuldeo2047** [comment]
Could use whitestorm for conveyor belt physics. http://codepen.io/Rick2047/pen/NjwqmO

Will check for variable velocities. 
> The velocity can change any time and body already in contact must get that velocity updated as well
