### ISSUE TITLE
CDN build missing modules

### ISSUE THREAD

**Issue by Shurlow** [WhitestormJS/whitestorm.js#245]
The current build hosted on [cdnjs](https://cdnjs.com/libraries/whitestorm.js/2.0.0-beta.8) doesn't seem to have all the modules built correctly. I am getting this error when including whs in a script tag:

```
Uncaught TypeError: WHS.ElementModule is not a constructor
    at white.js:4
```

Are modules like `WHS.ElementModule` intended to be included in the core api?

I understand that the recommended usage is via npm + webpack (totally agree), but maybe a functional cdn build with a simple explanation in the gh readme & [docs](https://whsjs.readme.io/docs#section-simple-is-better) is appropriate?

Otherwise maybe just exclude support for the cdn and remove the link on the readme?

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
@Shurlow , with beta8, would need to do this:
```
new WHS.app.ElementModule()
```
Let's talk on discord if you have any other issue

**Comment by Shurlow** [comment]
Gotcha, i'm just using the example setup as so:

```
const app = new WHS.App([
  new WHS.ElementModule(), // attach to DOM
  new WHS.SceneModule(), // creates THREE.Scene instance
  new WHS.CameraModule(), // creates PerspectiveCamera instance
  new WHS.RenderingModule() // creates WebGLRenderer instance
]);

app.start(); // run animation
```

**Comment by hirako2000** [comment]
yep, we try to keep examples as accurate as we can, but as we tidy up the API (backward compatible in 99% of the cases) if using a previous version, then it won't work.
I would say we just need to keep our CDN version and code pen examples up to date.

**Comment by Shurlow** [comment]
Hmm but I am using the most recent build on cdnjs 2.0.0-beta.8. Does this bundle still need to be transpiled with babel? I noticed the codepen example does this (https://codepen.io/sasha240100/pen/wgEXwN).

What is the purpose of the cdn if not to deliver to a client directly?

**Comment by hirako2000** [comment]
that's a good question. I always use babel with a bundler. 
Do you mind coming to discord a minute, I'm online
