### ISSUE TITLE
Rotating model with physics resets the rotation

### ISSUE THREAD

**Issue by thiervoj** [WhitestormJS/whitestorm.js#248]
When importing a model with `WHS.Model` and applying it a `rotation` in the constructor with `Physics`, the object is created with the correct rotation.
Then, when Physics is loaded, the rotation resets to the defaults.
Here is a pen showing the issue on the "arch" object (the `Cylinder`'s rotation works fine) : [https://codepen.io/jordanthiervoz/pen/vZBEWO](https://codepen.io/jordanthiervoz/pen/vZBEWO)

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [x] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
Fixed in #242. Will be soon in next release

**Comment by thiervoj** [comment]
The `rotation` issue seems to be resolved in the `beta 9.1` version.
I created an updated pen here : [https://codepen.io/jordanthiervoz/pen/yXymQb](https://codepen.io/jordanthiervoz/pen/yXymQb).

It looks like the physics are not updated for the collisions according to the rotation: the cylinder goes trough the model then bumps in the middle of it.

**Comment by sasha240100** [comment]
@thiervoj Open the issue in https://github.com/WhitestormJS/physics-module-ammonext . Looks like it is a scaling problem (data like `height`, `radiusTop`, ...)

**Comment by sasha240100** [comment]
@thiervoj Okay, I found the problem. You forgot to set `scale` on your concave mesh. [See this example](https://github.com/WhitestormJS/whitestorm.js/blob/beta/examples/basic/model/script.js#L18)

**Comment by thiervoj** [comment]
Oh, my bad ! Thanks for that :)
