### ISSUE TITLE
[Improve] Code style.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#3]
Guys, i have MANY troubles with my code style ;(
So i will be glad if somebody help me in developing engine.
**Contributors sought!**

All code in **src** folder. Compile with *gulp build* command.

You need: 
 - Contact me. alexbuzin88@gmail.com
 - Edit code in **src** folder.
 - Publish your change.
 - Contact me again.

TODO: 
- [x] Line wrap.
- [x] Prototypes fix.
- [x] Restructurize **libs**.

**Comment by sasha240100** [comment]
Published Gulpfile: https://github.com/sasha240100/WhitestormJS/commit/32da62c4673ccd16ef3a3508403792ca082557fd

**Comment by tiansijie** [comment]
nice project, eslint is a good option for coding style.

**Comment by sasha240100** [comment]
@tiansijie Thanks!:)
