### ISSUE TITLE
[Bug] Build 117 (0594835) fails on travis-ci

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#30]
I changed quotes to new ones (`) and now travis-ci throws new js parse error.
[MDN about quotes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Multi-line_strings)
**gulp build** throws same error.
![build 117 whitestormjs whitestorm js travis ci](https://cloud.githubusercontent.com/assets/7657429/12281024/597c84e6-b99b-11e5-854a-e8830e5fb281.png)

 Result of 0594835.

**Comment by Noctisdark** [comment]
This is an ES6 new feature an probably only supportes in Chrome and Mozilla, I think It is too early to use it, although there are transpilers out there .

**Comment by jackdalton** [comment]
Yes, [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) are not yet fully supported in many environments. We could potentially pipe our gulp tasks to Babel, [like I did with another project](https://github.com/jackdalton/e2d/blob/master/gulpfile.js#L41-L43).

It works flawlessly, and I see no obvious downside.

**Comment by jackdalton** [comment]
[This](https://gist.github.com/jackdalton/e3e11351d6c82b3841d6) would fix it (I just ran it through Babel), but it's quite unreadable.

**Comment by sasha240100** [comment]
We forgot 1 babel plugin.

**Comment by sasha240100** [comment]
Fixed.

**Comment by Noctisdark** [comment]
Great work, I think Including babel is a very good idea, It'll handle all polyfill for unsupported features for us, promises, extends and all !

**Comment by sasha240100** [comment]
@Noctisdark Thanks! ^^

**Comment by sasha240100** [comment]
@Noctisdark Thanks! ^^
