### ISSUE TITLE
[Bug] Babel adds "use strict"; code doesn't work!

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#31]
Console logs:
```javascript
whitestorm.js:1225 Uncaught TypeError: Cannot set property 'SimpleWorker' of undefined
game.js:5 Uncaught TypeError: Cannot read property 'init' of undefined
```

**Comment by sasha240100** [comment]
Removed simple-worker library. Anyway, we don't use it!

**Comment by Noctisdark** [comment]
How is this related to strict mode ?

**Comment by sasha240100** [comment]
@noctisdark Babel adds use strict. This small library worked before.

**Comment by Noctisdark** [comment]
Yes, but we probabl want to find what is it in this library that doesn't fit with strict mode.
since we do not use it it's okay.
