### ISSUE TITLE
Correct some meshes parameter types (TS)

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#318]
A few mesh types mistakenly named `parameter` some of the geometry properties. 
It should be `geometry`.

e.g Torus.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by noahcoetsee** [comment]
This is finished, so I'm gonna close this issue. (Sorry if i'm doing this wrong)
