### ISSUE TITLE
[Bug] Readme badges don't work

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#32]
Here is what i see:
![](https://drive.google.com/uc?export=view&id=0B3_nOx8jknTjVndteUpTT0h0OTg)

**Comment by jackdalton** [comment]
Restarted the badge server. I'm going to see if I can add a script to the server to keep Heroku from putting the server to sleep.

**Comment by jackdalton** [comment]
I added our app to [Kaffeine](http://kaffeine.herokuapp.com/)'s list, but [it'll have 6 hours of downtime no matter what we do](https://devcenter.heroku.com/articles/dyno-sleeping#quota).
