### ISSUE TITLE
[Improve] Add more tests

### ISSUE THREAD

**Issue by jackdalton** [WhitestormJS/whitestorm.js#34]
When I set up our test script, I just added a couple of tests; all these do is make sure that there are no syntax errors in the compiled output.

[Tests are run by Mocha](https://mochajs.org/#getting-started).

[Here's an example of a more comprehensive test suite](https://github.com/E2D/e2d/blob/master/test/test.js).

**Comment by sasha240100** [comment]
@jackdalton Do we need `test` folder?

**Comment by jackdalton** [comment]
@sasha240100 Yes, we do need `/test`.

**Comment by jackdalton** [comment]
I changed the label to hard, because it's going to be quite difficult getting all of these dependencies to run server side.
