### ISSUE TITLE
[Improve] Add lang attr on HTML tag

### ISSUE THREAD

**Issue by bdirl** [WhitestormJS/whitestorm.js#36]
**Lang attribute on HTML tag** helps people finding out if they will understand content without having to get deep into it.

For more information go to [W3] (http://www.w3schools.com/tags/att_global_lang.asp)

**What files to fix**: 
examples/basic.html
examples/basic_material.html
examples/basic_model.html
examples/fps.html
examples/plugin_example.html
examples/skybox.html
examples/stone_wall.html
or any new example *.html file

**How To Do it**:
 Add language attribute, for example, lang="fr"

**How to test it**:

1) Install [Vorlon.JS] (http://vorlonjs.com/?WT.mc_id=16538-DEV-sitepoint-article74)

2) add the following line into your test HTML file:

'<  script src="http://localhost:1337/vorlon.js"  >' '<  /script  >'

3) Once Vorlon.JS is done installing, run the server:

$ vorlon

4) With the server is running, open http://localhost:1337 in your browser to see the Vorlon.JS dashboard.

5) Open your test html file,  and it should appear on the Vorlon.JS dashboard.

6) In the dashboard, click on the button **Best Practice: Accessibility**  and check the 
**add lang attr on HTML tag**

**Comment by sasha240100** [comment]
@bdirl I think it will be a good start to work with us:) Do it!

**Comment by bdirl** [comment]
Added the following into each *.html file:

'< html lang="en-US">'
