### ISSUE TITLE
Font type error for Text component

### ISSUE THREAD

**Issue by looading** [WhitestormJS/whitestorm.js#360]
Describe your issue here.
The type whether it should be `Font | Promise<Font>` here
https://github.com/WhitestormJS/whs.js/blob/fe64f409e2503ccef44bc8ec2a3eb8591ca61793/types/components/meshes/Text.d.ts#L19
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
Adjusted.
Thanks!
