### ISSUE TITLE
Don`t know whether resources has already loaded.

### ISSUE THREAD

**Issue by looading** [WhitestormJS/whitestorm.js#362]
Describe your issue here.
I don't know whether resources has already completed the loading when I want to add animation to `components/meshes/text`.

This is an error has occurred.
![image](https://user-images.githubusercontent.com/9467452/33543474-253c3a8a-d912-11e7-8128-e1d53d44311f.png)

Then i found that `component.isDeffered` is always  `true`.
https://github.com/WhitestormJS/whs.js/blob/6cd98b4639bd9ae2444907a3f1567809728f2a14/src/core/Component.js#L91

why not reset `component._wait` to an empty Array while the promise is done?

``` javascript
  defer(func) {
    if (this.isDeffered) this.wait().then(() => { func(this); this._wait = [] });
    else func(this);
  }
```
Then i can avoid error.
``` typescript
   this._loop = new Loop((clock) => {
      if (!hostComponent._instance.isDeffered) {  // hostComponent._instance => Text instance
        this.loop(hostComponent, clock, this.secen); 
      }
   }, this.useLock);
```
Do you have other better way?

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [x] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@looading You may need to do the following:
```js
new WHS.Text({
 // ...
}).addTo(app).then(text => {
 // In this scope text.native is already defined and you can do any manipulations with animations.
});

// Another situation is to do like that:

const text = new WHS.Text({
 // ...
});

text.defer(() => {
  // callback.
});
```

Both variants are useful and provide the same idea. `component._wait` contains resolved/rejected/pending promises, if all promises are resolved -> defer() called. What is the reason of making `._wait` empty?

**Comment by looading** [comment]
@sasha240100 Thanks! I got it.
