### ISSUE TITLE
the URL for WHS is invalid address on the sites.

### ISSUE THREAD

**Issue by wangzry** [WhitestormJS/whitestorm.js#364]
Describe your issue here.
As you have changed the url of WHS from whsjs.io to whs.io, the links to WHS  are invalid address on some pages,for example,the docs of [examples](https://whs-dev.surge.sh/examples/), and the link on [github](https://github.com/WhitestormJS).
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@wangzry Thank you for mentioning this, I’ll try to fix that soon!
