### ISSUE TITLE
Wrong project url on WhitestormJS Framework github group

### ISSUE THREAD

**Issue by antoniocapelo** [WhitestormJS/whitestorm.js#367]
Not really an issue, but only after some frustrated navigations I noticed that the url on the githbug group page is wrong (it's https://whsjs.io/ instead of https://whs.io, which at first sight seems the same). 

I was always trying to get back to the projects' homepage using that link and noticing showed up 😅 Figured I should warn so that I'd be last one experiencing it.

By the way, nice work with the framework!

**Comment by sasha240100** [comment]
@antoniocapelo Thanks! Fixed.
