### ISSUE TITLE
Help on using modules for extending component behavior

### ISSUE THREAD

**Issue by antoniocapelo** [WhitestormJS/whitestorm.js#368]
Hi! From what I understood, modules are a very useful piece of code that, amongst other things, let us enhance our components' behavior. 

My current scenario is trying to make a 'responsive module' where I would add a callback to `ResizeModule` instance present on the app so that the component using it could have it's geometry dimension updated for certain breakpoints. Does this make sense?

I'm having trouble accessing the App's modules from inside the component module, is this possible?

I'm using react-whs and bellow there are some snippets from my code.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [x] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [x] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details> 

My main app.js:

```js
                <App modules={[
                    new WHS.SceneModule(),
                    new WHS.DefineModule('camera', new WHS.PerspectiveCamera({
                        fov: 75,
                        aspect: window.innerWidth / window.innerHeight,
                        position: new THREE.Vector3(0, 0, 80)
                      })),
                    new WHS.DefineModule('ambient light', new WHS.AmbientLight({
                        light: {
                            intensity: 0.3
                        }})),
                    new WHS.RenderingModule({...}),
                    new WHS.ResizeModule(),
                    new WHS.VirtualMouseModule(),
                    new WHS.OrbitControlsModule()]}
                    refApp={(app) => { this.app = app; }}>
                    <TestComponent />
               </App>
```

My component that will be using the said module:

```js
import React, { Component } from 'react';
import * as THREE from 'three';
import * as WHS from 'whs';
import { Sphere } from 'react-whs';
import ResponsiveDimensionModule from './ResponsiveDimensionModule';

export default class TestComponent extends Component {
    render() {
        return (
            <Sphere
                geometry={{
                    radius: 2
                }}

                material={new THREE.MeshBasicMaterial({
                    color: this.props.color,
                })}

                modules={[
                    new ResponsiveDimensionModule(),
                ]}

                {...this.props}
            />
        )
    }
}

```

My current code for the module is still very barebones since I could't progress without the manager modules:
```js
export default class ResponsiveDimensionModule {
    manager(manager) {
       // at this point, manager.modules is empty, so I cannot make .get('resize') to then run the .addCallback 
    }
}
```

I've tried passing the manager that comes from `this.props.parent.manager` to the module constructor on the component level but without any luck (manager.modules was still empty).

Hope I've explained myself clearly. If the modules are not meant to be used like this, please say so, since I've chose WHS to ease this type of work (dealing with resizes, reacting to audio input, etc).

Cheers

**Comment by sasha240100** [comment]
@antoniocapelo Hey! From what I understand, you're looking for a way to use `ResizeModule#addCallback(func)` from `ResponsiveDimensionModule`.

Here's what you have to know:
  1. App and Sphere have different "managers".
  2. What you could do is to pass app (or app manager) inside `ResponsiveDimensionModule`:

### Option 1

```js
new ResponsiveDimensionModule(app)
```

And use it's manager inside your module:

```js
export default class ResponsiveDimensionModule {
    constructor(app) {
        this.app = app;
    }

    manager(manager) {
       const resizeModule = this.app.manager.use('resize'); // or this.app.use('resize') [shorter]
    }
}
```

### Option 2
How about defining "app" as module dependency for the whole component?

```js
// ...
  modules: [
    new WHS.DefineModule('app', app),
    new ResponsiveDimensionModule() // get app there using "manager.get('app')"
    // To get ResizeModule -> "manager.get('app').use('resize')"
  ]
// ...
```

### Option 3 [bridges API]
> Experimental.

An extended idea of what was described in Option 2, but using "bridges API".
Write a simple module for WHS.App (something like this):

```js
class AppBridgeModule {
  bridge = {
    onAdd(addedComponent, self) { // in this case "self" is an AppBridgeModule context.
      return new Promise(resolve => {
        function traverse(component) {
          component.applyBridge({app: self.handler});
          component.children.forEach((child) => traverse(child));
        }

        traverse(addedComponent);
        resolve();
      });
    }
  }
}
```

JSX:
```js
<App
  modules={[
    // ...
    new AppBridgeModule()
  ]}
>
  <Sphere
    modules={[
      new ResponsiveDimensionModule()
    ]}
  </Sphere>
</App>
```

ResponsiveDimensionModule:

```js
export default class ResponsiveDimensionModule {
    bridge = {
        app(app) {
            const resizeModule = app.use('resize');
        }
    }
}
```

And then you can use `ResponsiveDimensionModule` in any hierarchy place inside `<App/>`.
If you have some quick questions - better ping me in discord. I respond faster there.

Choose the option you like;)

**Comment by antoniocapelo** [comment]
@sasha240100 thanks! I ended up figuring the Option 1 by myself 🎉 but I think your two other options are more elegant 😃 

But I only could figure that out when I tried it in vanilla WHS and not using react-whs. The thing is (I think) that on react-whs our `app` is not yet defined when declaring the components on the `render()` method. So I cannot do 

```
<SomeComponent 
    ....
    modules={[new WHS.DefineModule('app', this.app)]} />
```

Because at that time, the `refApp` callback hasn't run yet. This forces me to make most of the code on the `componentDidMount` method of the container — creating the Meshes without the react wrappers and adding it manually to the app. If most of the code is meant to be written on the `componentDidMount`, I'm not making use of the jsx components, Does this make sense? 

I'm just starting a project using the whs + react-whs solution, so if react-whs is not stable enough, I can just switch to plain WHS...

**Comment by antoniocapelo** [comment]
by the way, I think on that line
```js
component.applyBridge({app: self.handler});
```
we need to add `.app`to the end, right?

```js
component.applyBridge({app: self.handler}).app;
```

**Comment by sasha240100** [comment]
> we need to add .appto the end, right?

@antoniocapelo If you modify it inside the "bridge" function and want to return it and use - yep, ok.
But in this case - No need

**Comment by sasha240100** [comment]
@antoniocapelo For `react-whs` consider Option 3, as it completely relies on internal features of modules. You also have [`afterMount`](https://github.com/WhitestormJS/react-whs/blob/master/src/App.js#L38) prop function support in `<App/>`.

> I'm just starting a project using the whs + react-whs solution, so if react-whs is not stable enough, I can just switch to plain WHS...

My recommendation is to use `WHS` without react overlay for big projects. But I would also like if you help me to improve `react-whs` by contributing 😎🙂
