### ISSUE TITLE
[Improve] Use aria attributes

### ISSUE THREAD

**Issue by bdirl** [WhitestormJS/whitestorm.js#37]
**Accessible Rich Internet Applications (ARIA)**

**Use accessibility attributes** like aria-label to provide meaningful information for people with visual disabilities.

For more information go to [ARIA in HTML] (https://www.w3.org/TR/html-aria/) 

**What files to fix**: 
examples/basic.html
examples/basic_material.html
examples/basic_model.html
examples/fps.html
examples/plugin_example.html
examples/skybox.html
examples/stone_wall.html
or any new example *.html file

**How To Do it**:
 Examples are on Mozilla website [Web Technology For Developers] (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

**How to test it**:

1) Install [Vorlon.JS] (http://vorlonjs.com/?WT.mc_id=16538-DEV-sitepoint-article74)

2) add the following line into your test HTML file:

'<  script src="http://localhost:1337/vorlon.js"  >' '<  /script  >'

3) Once Vorlon.JS is done installing, run the server:

$ vorlon

4) With the server is running, open http://localhost:1337 in your browser to see the Vorlon.JS dashboard.

5) Open your test html file,  and it should appear on the Vorlon.JS dashboard.

6) In the dashboard, click on the button **Best Practice: Accessibility**  and check the 
**use aria attributes**

**Comment by bdirl** [comment]
Other people suggestions:
Etienne Margraff ‏@meulta => http://html5doctor.com/using-aria-in-html/
Matteo Pescarin @ilpeach  => https://www.w3.org/TR/wai-aria/

**Comment by bdirl** [comment]
sasha240100, Please comment this issue and close it.

There are a lot of rules that should be applied to any html file and allow people with visual disability to read those pages. When I said read, ARIA allows The Screen Readers to focus and navigate the person through HTML page elements (text, buttons, links, forms, tables, menus, .... The best site with all applied ARIA elements is the https://www.gov.uk/.

Watching the YouTube presentation of  Karl Groves about Accessibility Testing Tools and reading the posts on his blog about it, I found being uncomfortable about ARIA implementation to the WHS game. Someone could sue your website if you did not implement ARIA properly. It is true.

In the case of WHS, fps.html does not contain any of the elements (button, menuitem, radio, etc) as it is specified in http://html5doctor.com/using-aria-in-html/. As WHS contains images only, allowed ARIA role attributes are NONE, and allowed ARIA state and property attributes are Global aria-* attributes. 

I suppose that WHS will contain in the future some pages asking visitors to sing up, log in etc. In that case, the following elements should be applied to *.HTML pages  (the example's taken from http://www.heydonworks.com/article/practical-aria-examples ):

```
<form action="">
  <fieldset>
    <legend>Login form</legend>
    <div>
      <label for="username">Your username</label>
	  <input type="text" id="username" aria-describedby="username-tip" required />
	  <div role="tooltip" id="username-tip">Your username is your email address</div>
	</div>
	<div>
	  <label for="password">Your password</label>
	  <input type="text" id="password" aria-describedby="password-tip" required />
	  <div role="tooltip" id="password-tip">Was emailed to you when you signed up</div>
	</div>
  </fieldset>
</form>
```

etc.

References:
https://www.youtube.com/watch?v=_uq6Db47-Ks
http://www.karlgroves.com/
http://www.karlgroves.com/2015/09/17/sue-everyone/
http://w3c.github.io/aria-in-html/

**Comment by sasha240100** [comment]
@bdirl Actually, it already contains ;) Feel free to edit: https://github.com/WhitestormJS/whitestormjs.github.io
