### ISSUE TITLE
Update to three.js r90

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#370]
Update three.js dependency, it now sits at r90.0
A number of fixes and improvements were made since r87.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@hirako2000 is it already in dev by you or better I fix it in days?

**Comment by hirako2000** [comment]
PR #371
I've checked the example, they seem to run fine.

I wanted to fix the Alien example as the animation on the example host is broken - but it's working fine for me locally.
Can you check things are running fine? also, I have not pushed the built files, just src.

**Comment by sasha240100** [comment]
@hirako2000 Sure, will do in a hour or two.

**Comment by hirako2000** [comment]
Verified? Can we close?
