### ISSUE TITLE
Shading broken in v2.0 demo with v2.1.9

### ISSUE THREAD

**Issue by cawoodm** [WhitestormJS/whitestorm.js#373]
The demo at https://codepen.io/sasha240100/pen/JELBGX works nicely:
![image](https://user-images.githubusercontent.com/498834/38140903-4732b91e-3436-11e8-9fe8-440ab96cf4ae.png)

However, updating to the v2.1.9 CDN: https://cdnjs.cloudflare.com/ajax/libs/whitestorm.js/2.1.9/whs.js we lose shading:
![image](https://user-images.githubusercontent.com/498834/38140887-3cf79c1c-3436-11e8-83a0-1f995702b255.png)
https://codepen.io/anon/pen/YaaaKj?editors=0010

What am I missing or is there a v2.1.9 demo somewhere?

**Comment by sasha240100** [comment]
@cawoodm Yes, all the props from the `light: {}` where moved to the root object. Fixed -> https://codepen.io/sasha240100/pen/GxxGwX?editors=0010

**Comment by cawoodm** [comment]
Thanks!
