### ISSUE TITLE
[Improve] Define platform icons

### ISSUE THREAD

**Issue by bdirl** [WhitestormJS/whitestorm.js#38]
**Platform icons** helps user pinning your website with an icon that fits well on mobile device home.

**What files to fix**: 
examples/basic.html
examples/basic_material.html
examples/basic_model.html
examples/fps.html
examples/plugin_example.html
examples/skybox.html
examples/stone_wall.html
or any new example *.html file

**How To Do it**:
add Apple - iOS icons by adding link tags like 
'< link rel="apple-touch-icon-precomposed" href="youricon" sizes="57x57" />'

add Microsoft - Windows tiles by adding meta tags like 
'< link name="msapplication-square150x150logo" content="yourimage" />'

**How to test it**:

1) Install [Vorlon.JS] (http://vorlonjs.com/?WT.mc_id=16538-DEV-sitepoint-article74)

2) add the following line into your test HTML file:

'<  script src="http://localhost:1337/vorlon.js"  >' '<  /script  >'

3) Once Vorlon.JS is done installing, run the server:

$ vorlon

4) With the server is running, open http://localhost:1337 in your browser to see the Vorlon.JS dashboard.

5) Open your test html file,  and it should appear on the Vorlon.JS dashboard.

6) In the dashboard, click on the button **Best Practice: MOBILE WEB**  
and check the **define platform icons**

**Comment by sasha240100** [comment]
@bdirl All those icons you can find in `development/art/logo/` folder.

**Comment by bdirl** [comment]
Added the following to all *.html files:
<pre>
<link rel="apple-touch-icon-precomposed" href="http://whitestormjs.xyz/favicon.ico" sizes="57x57" />
 <meta name="msapplication-square150x150logo" content="../development/art/logo/ico150.png" />
</pre>
