### ISSUE TITLE
 [ts] Property 'DefineModule' does not exist

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm.js#386]
Getting a ts error

```
 [ts] Property 'DefineModule' does not exist on type 'typeof import("node_modules/whs/types/index")'.
```

This module is not defined in types
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by shaochun** [comment]
Thanks for the quick fix!
