### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by tommhuth** [WhitestormJS/whitestorm.js#391]
Has this project been abandoned? Examples don't seem to work, and recent activity seem to be scarce. Any news on the v3.0.0?

**Comment by hirako2000** [comment]
Hi @tommhuth

Not dead, less activities lately for a few reasons, whs 2 is pretty stable and not pressing need to add crutial features.

Road map  includes fixing the examples nested links, they broke during a revamp of the example navigation UI, it looks better than before. I believe Alex will fix the glitch, but we welcome PRs as always. 

With regard to v3, I know Alex had some interesting plans, he might comment on that.

**Comment by sasha240100** [comment]
Hi all,
Yes, we are on a way to release whs 3.x.x, so I’m guessing the project is
live at this point

**Comment by tommhuth** [comment]
Good to hear. The API looks a lot more forward leaning than other 3D libraries around, but the documentation seems to be missing. You mention Physi.js library, but I cannot find any docs covering that, or how that is supposed to be integrated (where's that PHYSICS object coming from if you're using ES modules?).

**Comment by sasha240100** [comment]
@tommhuth https://github.com/WhitestormJS/physics-module-ammonext

**Comment by tommhuth** [comment]
So that package also supports Physi.js or has that be superseded by Ammo?

**Comment by sasha240100** [comment]
That package is an adaptation of Physijs to whs.js. It uses Ammo under its
core

**Comment by Andrews54757** [comment]
@hirako2000 Hello! Could you possibly take a look at my issue at that library?

https://github.com/WhitestormJS/physics-module-ammonext/issues/16

I posted about a typo, and it seems like it has not been addressed. This error causing typo was where `.length` was replaced with `.lenght`. I noticed that this went UNNOTICED SINCE INITIAL COMMIT!

https://github.com/WhitestormJS/physics-module-ammonext/blob/2d2bf1adbaa4e36d94aa8efa1caa32d24cf74f75/src/worker.js#L1537

Has this library ever been thoroughly tested before?

**Comment by segg21** [comment]
Dear @Andrews54757,

> For your concern of [worker.js#L1537](https://github.com/WhitestormJS/physics-module-ammonext/blob/2d2bf1adbaa4e36d94aa8efa1caa32d24cf74f75/src/worker.js#L1537), we've been working very very hard (_actually a few years_), to release 3.x.x. Unfortunately, since this project is old, I will not make this change. Sorry for the delay in updates, there hasn't been proper maintenance/control nor stability. Please wait until next release, which there's no ETA. Sorry for the inconvenience.

**Comment by sasha240100** [comment]
See https://github.com/WhitestormJS/whs.js/issues/395
I'm closing this issue
