### ISSUE TITLE
Jpg Textures look solid color

### ISSUE THREAD

**Issue by zardilior** [WhitestormJS/whitestorm.js#394]
Describe your issue here.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [x] Question
 - [ ] Discussion

------
Any reason why a loaded texture with the texture module would appear as solid color brown on a model?
<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
A few reasons would come to mind:

- mistake on renderer config, try on a clean slate (someone banged his head on the wall on this until realizing some issue elsewhere in the code.
- UV map issue when trying to map the texture, try with a very simple mesh first along with a texture not needing UVs
