### ISSUE TITLE
[Improve] Use responsive approaches

### ISSUE THREAD

**Issue by bdirl** [WhitestormJS/whitestorm.js#40]
Even if your website target only certain devices, you may have users with unexpected devices or screen ratio.

For more information see [Responsive Web Design] (https://developers.google.com/webmasters/mobile-sites/mobile-seo/responsive-design?hl=en)

**What files to fix**: 
examples/basic.html
examples/basic_material.html
examples/basic_model.html
examples/fps.html
examples/plugin_example.html
examples/skybox.html
examples/stone_wall.html
or any new example *.html file

**How To Do it**:
Check if  your css (either files or inline) use any media queries.
Check if your link tags use any media queries.

**How to test it**:

1) Install [Vorlon.JS] (http://vorlonjs.com/?WT.mc_id=16538-DEV-sitepoint-article74)

2) add the following line into your test HTML file:

'<  script src="http://localhost:1337/vorlon.js"  >' '<  /script  >'

3) Once Vorlon.JS is done installing, run the server:

$ vorlon

4) With the server is running, open http://localhost:1337 in your browser to see the Vorlon.JS dashboard.

5) Open your test html file,  and it should appear on the Vorlon.JS dashboard.

6) In the dashboard, click on the button **Best Practice: MOBILE WEB**  and check the 
**use responsive approaches**

**Comment by bdirl** [comment]
sasha240100,
Once you said on the Slack, that WHS should be considered as a game for the desktop computers, meaning a big screen with high resolution. Having that fact in mind, to fix #40 the following line should be added to any *.html file of whitestorm.js game:

'< style>
  @media only screen and (min-width: 10000px; orientation: landscape) {
  }
'< /style>

@media includes the following media type of devices:
all	        Used for all media type devices
print	        Used for printers
screen	Used for computer screens, tablets, smart-phones etc.
speech	Used for screenreaders that "reads" the page out loud

Print and Speech are excluded from WHS.

If you want, you can add other parameters to the screen, such as:

aspect-ratio	The ratio between the width and the height of the viewport
color	The number of bits per color component for the output device
color-index	The number of colors the device can display
device-aspect-ratio	The ratio between the width and the height of the device
device-height	The height of the device, such as a computer screen
device-width	The width of the device, such as a computer screen
grid	Whether the device is a grid or bitmap
height	The viewport height
max-aspect-ratio	The maximum ratio between the width and the height of the display area
max-color	The maximum number of bits per color component for the output device
max-color-index	The maximum number of colors the device can display
max-device-aspect-ratio	The maximum ratio between the width and the height of the device
max-device-height	The maximum height of the device, such as a computer screen
max-device-width	The maximum width of the device, such as a computer screen
max-height	The maximum height of the display area, such as a browser window
max-monochrome	The maximum number of bits per "color" on a monochrome (greyscale) device
max-resolution	The maximum resolution of the device, using dpi or dpcm
max-width	The maximum width of the display area, such as a browser window
min-aspect-ratio	The minimum ratio between the width and the height of the display area
min-color	The minimum number of bits per color component for the output device
min-color-index	The minimum number of colors the device can display
min-device-aspect-ratio	The minimum ratio between the width and the height of the device
min-device-width	The minimum width of the device, such as a computer screen
min-device-height	The minimum height of the device, such as a computer screen
min-height	The minimum height of the display area, such as a browser window
min-monochrome	The minimum number of bits per "color" on a monochrome (greyscale) device
min-resolution	The minimum resolution of the device, using dpi or dpcm
min-width	The minimum width of the display area, such as a browser window
monochrome	The number of bits per "color" on a monochrome (greyscale) device
orientation	The orientation of the viewport (landscape or portrait mode)
overflow-block	How does the output device handle content that overflows the viewport along the block axis (added in Media Queries Level 4)
overflow-inline	Can content that overflows the viewport along the inline axis be scrolled (added in Media Queries Level 4)
resolution	The resolution of the output device, using dpi or dpcm
scan	The scanning process of the output device
update-frequency	How quickly can the output device modify the appearance of the content (added in Media Queries Level 4)
width	The viewport width


I wasn't sure how many of them would be appropriate for the WHS, and I only included min-with and orientation.

Please, comment this and advise if anything should apply for the whitestorm.js.
Otherwise, I think that this issue is now fixed.

**Comment by sasha240100** [comment]
@bdirl Thanks!
