### ISSUE TITLE
[Improve] Try bundling your files

### ISSUE THREAD

**Issue by bdirl** [WhitestormJS/whitestorm.js#41]
**Multiple http requests makes your site slower**, especially on mobile devices.

**What files to fix**: 
examples/basic.html
examples/basic_material.html
examples/basic_model.html
examples/fps.html
examples/plugin_example.html
examples/skybox.html
examples/stone_wall.html
or any new example *.html file

**How To Do it**:
 Preliminary tests with Vorlon.JS show that there are more than 5 scripts files in a page with the recommendation "consider bundling your scripts".

**How to test it**:

1) Install [Vorlon.JS] (http://vorlonjs.com/?WT.mc_id=16538-DEV-sitepoint-article74)

2) add the following line into your test HTML file:

'<  script src="http://localhost:1337/vorlon.js"  >' '<  /script  >'

3) Once Vorlon.JS is done installing, run the server:

$ vorlon

4) With the server is running, open http://localhost:1337 in your browser to see the Vorlon.JS dashboard.

5) Open your test html file,  and it should appear on the Vorlon.JS dashboard.

6) In the dashboard, click on the button **Best Practice:  PERFORMANCE**  and check the 
**try bundling your files**

**Comment by sasha240100** [comment]
@bdirl Only `examples/fps.html` needs it. Other ones are basic, so there are less requests.

**Comment by sasha240100** [comment]
@bdirl Have you done it?

**Comment by bdirl** [comment]
sasha240100, Please leave a comment and close this issue.

#41 should be renamed from an issue to the rile as WHS is still in the development phase, and the rule is the following:

The load time of any WHS *.html page should be less than 1 second. To achieve that, the *.html page should have:

1) less than 5 javaScript files, all of them should be the latest versions, and compressed, for an example *.html should have three.min.js, then whitestorm.min.js, etc.

2) if there are more than 5 javaScript files in a fps.html page (as we have at the moment), we should use gulp build and concatenate and compress all those javaScript files to the one only. The order of the files should be the same as we specified in the existing fps.html file. It is the same process as we do to make whitestorm.min.js (one *min.js file made of many *.js files).

3) next, as fps.html is going to have images or call other *.css files, all of them should be compressed too.

4) there is also a recommendation to encode the whole fps.html (gzip) if it is too complex and contains many components (*.js, *.css, *.png, etc).

For now, fps.html is having more and more *js scripts with any new version, so I will not add to gulp build process anything and will leave that to the end of the WHS development, as then you will have a clear picture what fps.html would contain.

**Comment by sasha240100** [comment]
@bdirl 
1) For now we use examples(tests) at most for developing WhitestormJS engine while it is a development version yet. So it is better to use .js files as we can see a clear code and find errors faster. 
2) Let's make at least beta-version first, or we can just make examples for testing separately from examples for users.
3) Agreed.
4) Hmmm... Users need to see the source of examples. They will learn how to work with an engine by examples.

5) Sure. I'll make it clear in a few next commits.
