### ISSUE TITLE
[Bug] FPS Example not working in Safari

### ISSUE THREAD

**Issue by noxowe** [WhitestormJS/whitestorm.js#45]
![Dev tools console](https://cloud.githubusercontent.com/assets/7858366/12702893/3a013640-c835-11e5-94c0-e7b0c084e319.png)

**Comment by jackdalton** [comment]
Interesting. Looking past the blocker div, it looks like there's no terrain. What happens if you click the blocker div (anywhere on the page)?

**Comment by noxowe** [comment]
@jackdalton I get a weird error: 
TypeError: undefined is not an object (evaluating 'element.requestPointerLock') on line 3922 of Whitestorm.js

**Comment by jackdalton** [comment]
[Line 3922](https://github.com/WhitestormJS/whitestorm.js/blob/master/build/whitestorm.js#L3922) handles pointer lock, and it looks like that comes from [line 257](https://github.com/WhitestormJS/whitestorm.js/blob/master/src/Controls/FPSControls.js#L257) of `FPSControls.js`. It looks like `element` is undefined.

`element` is defined [here](https://github.com/WhitestormJS/whitestorm.js/blob/master/src/Controls/FPSControls.js#L220), but only if this condition is met:

```javascript
'pointerLockElement' in document || 'mozPointerLockElement' in document || 'webkitPointerLockElement' in document
```

Can you paste that above code into your console, and tell me the result? It'll either be `true` or `false`.

**Comment by noxowe** [comment]
@jackdalton false

**Comment by jackdalton** [comment]
@noxowe Hmm... What version of Safari are you using?

**Comment by noxowe** [comment]
@jackdalton latest, my OSX is always updated to the latest version and I use Macbook Air 2015 edition

**Comment by jackdalton** [comment]
@noxowe Yeah, I'm seeing the same thing on BrowserStack.
![image](https://cloud.githubusercontent.com/assets/10249860/12703018/59dd17ee-c7f5-11e5-8dd9-b22dce9b2c86.jpg)

**Comment by noxowe** [comment]
@jackdalton this seems to be a version before Yosemite I think. This isn't my version

**Comment by jackdalton** [comment]
@noxowe Yep, it was on Mavericks.

**Comment by jackdalton** [comment]
@noxowe It looks like [Safari doesn't support the PointerLock API](http://caniuse.com/#feat=pointerlock).

**Comment by jackdalton** [comment]
@noxowe Can you tell me if [this](http://mrdoob.github.io/three.js/examples/misc_controls_pointerlock.html) works?

**Comment by noxowe** [comment]
@jackdalton "Your browser doesn't seem to support Pointer Lock API" with a bunch of cubes in the background

**Comment by jackdalton** [comment]
@noxowe That confirms it then, it's a lack of compatibility on Safari's end. Thanks for reporting this. I added a more specific warning in 2ea220a.

**Comment by OKNoah** [comment]
Skybox doesn't work either, and neither work in Safari Technology Preview.

**Comment by jackdalton** [comment]
@OKNoah Are there any error messages in the console?

**Comment by sasha240100** [comment]
@jackdalton Where have you been?

**Comment by jackdalton** [comment]
@sasha240100 I've been gone for a while, but I think I'm back.

**Comment by sasha240100** [comment]
@jackdalton Let's move to slack

**Comment by jackdalton** [comment]
@OKNoah If it's a matter of incompatibility with the PointerLock API, then you should see the following warning: "Your browser does not support the PointerLock API," which was added by 2ea220a.

**Comment by jackdalton** [comment]
No reply after 11 days. Closing.

**Comment by OKNoah** [comment]
@jackdalton I don't see that warning, just the tornado animation perpetually.

**Comment by jackdalton** [comment]
@OKNoah Is there anything else in the console?

**Comment by OKNoah** [comment]
@jackdalton Here are the console errors. No messages.

```[Error] TypeError: Super expression must either be null or a function, not undefined
	_inherits (whs.wagner.js:35:109)
	(anonymous function) (whs.wagner.js:63)
	global code (whs.wagner.js:230)
[Error] SyntaxError: Unexpected token '...'. Expected a parameter pattern or a ')' in parameter list.
	(anonymous function) (whs.preload.js:21)
[Error] ReferenceError: Can't find variable: Preloader
	global code (game.js:1)
```

**Comment by sasha240100** [comment]
@OKNoah Possibly it happened after the original link changed. We use deploybot to run examples in web immediately after they are pushed to `master` branch. It doesn't delete old files, so it just creates/overwrites new. Try [new link](http://192.241.128.187/current/examples/fps/shooter/). If the error is still there - let me know. I see by your log that it is an old example which is located by http://192.241.128.187/current/examples/fps.html so it can't reach files by their old location.
