### ISSUE TITLE
[Bug] Adding AmbientLight to scene breaks the build

### ISSUE THREAD

**Issue by rongierlach** [WhitestormJS/whitestorm.js#54]
```
GAME.ambient_light = GAME.AmbientLight {
    light: { color: 0x080808 }
}
```

Throws: 
Uncaught TypeError: Cannot read property 'mapSize' of undefined

**Comment by sasha240100** [comment]
@rongierlach I'll fix it with update to Three.js r74. (In 15 minutes)

**Comment by sasha240100** [comment]
@rongierlach Try now: http://192.241.128.187/current/examples/fps.html

**Comment by rongierlach** [comment]
Looks like latest push is causing a looping error for me:

Uncaught TypeError: Cannot read property 'camera' of undefined

**Comment by sasha240100** [comment]
@rongierlach Can you give me a link to your code?

**Comment by rongierlach** [comment]
The blocks at Line 114 or Line 141

https://github.com/rongierlach/gulp-frontend/blob/whitestorm/src/coffeescripts/main.coffee

**Comment by sasha240100** [comment]
@rongierlach I'll take a look

**Comment by sasha240100** [comment]
@rongierlach How can i install&start your app?

**Comment by rongierlach** [comment]
Something to this effect:
```
git clone -b whitestorm https://github.com/rongierlach/gulp-frontend.git
cd gulp-frontend/
npm install -g gulp
npm install
bower install
gulp
```
Let me know if you have any trouble!

**Comment by sasha240100** [comment]
@rongierlach 

```console
Error: Cannot find module 'webpack-core/lib/ReplaceSource'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)

```

**Comment by sasha240100** [comment]
@rongierlach Nevermind, Fixed that

**Comment by sasha240100** [comment]
@rongierlach Almost ready
![image](https://cloud.githubusercontent.com/assets/7657429/13471417/297e63b4-e0b9-11e5-91ba-5e20a29e25b0.png)

**Comment by sasha240100** [comment]
@rongierlach This, right?
![image](https://cloud.githubusercontent.com/assets/7657429/13471455/59c90344-e0b9-11e5-9ef1-882b76db4fd3.png)

**Comment by sasha240100** [comment]
Ok, now i see

**Comment by rongierlach** [comment]
@sasha240100 

Sorry I'm late to respond, at working and looking at github when I get the second.
You'll need to uncomment one of the blocks where an AmbientLight is added.

Lines 114 - 116 for instance.

**Comment by sasha240100** [comment]
@rongierlach Solved!
![image](https://cloud.githubusercontent.com/assets/7657429/13472682/ab858540-e0be-11e5-9af5-8b7906094739.png)

**Give me write access and i will push it to your repo.**
![image](https://cloud.githubusercontent.com/assets/7657429/13472793/13118b14-e0bf-11e5-97a0-32934c83b719.png)

**Comment by sasha240100** [comment]
@rongierlach I updated your three.js version(r73 -> r74) and Wagner.js(they made changes after r74 was released)

**Comment by sasha240100** [comment]
@rongierlach https://github.com/rongierlach/gulp-frontend/pull/1 - Made a pull request. No need for opening access for me now.

**Comment by rongierlach** [comment]
Thanks!

**Comment by sasha240100** [comment]
@rongierlach You're welcome!

**Comment by sasha240100** [comment]
@rongierlach I will release docs this week.

**Comment by sasha240100** [comment]
@rongierlach whitestormjs.xyz - docs are here.
