### ISSUE TITLE
[Improve] WHS.Shape/WHS.Light remove() need to set null to it's root.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#64]
Remove funtion only removes object from scene now:

```javascript
remove() {
		
	this.root.scene.remove( this.mesh );

	return this;

}
```

It should remove object also from WHS.World's children array and remove object's (shape's/light's) root value.

**Comment by sasha240100** [comment]
**UPDATE**

WHS.Shape's retrieve() function add's shape back to this.root (WHS.World) object. But it won't because we remove `this.root` value each time we remove object. You should also add something like `this.last_root` that will always store WHS.World in which this shape was last time.

*The same for `WHS.Light`*

**Comment by Noctisdark** [comment]
It should be removed from ```this.root.children``` and ```this.root.modellingQueue```.
Something, like this will do
```
let index = this.root.modellingQueue.indexOf( this );
if( index !== -1 ) {
  this.root.modellingQueue.splice( index, 1 );
  this.root.children.splice ( this.root.children.indexOf( this, 1 ); //Since every object is put there
}
```
Why should we remove object light and shape value ?

**Comment by sasha240100** [comment]
@Noctisdark Where have you been? Join our discussion in slack!

**Comment by sasha240100** [comment]
@Noctisdark We shouldn't remove light/shape value. We should remove it's root property value.

``javascript
 // WHS.Shape object

{
 //...tratata
 mesh: {},
 root: WHS.World // We should set it to null
}

```

**Comment by sasha240100** [comment]
@Noctisdark The problem is that remove function removes object only from scene in `WHS.World` object, but it also should remove object from children array in that `WHS.World` and should delete own root property or set to null. 

**When object is added to WHS.World**:
```javascript

// WHS.World that consist WHS.Box:
{
   ...
   children: [WHS.Box],
   scene: {
      ...
      children: [THREE.Box],
      ...
   }
   ...
}

// WHS.Box that is in WHS.World:
{
   ...
   root: WHS.World
   ...
}
```

**And another situation:**
```javascript

// WHS.World that doesn't consist WHS.Box:
{
   ...
   children: [],
   scene: {
      ...
      children: [],
      ...
   }
   ...
}

// WHS.Box that is not in WHS.World:
{
   ...
   root: null
   ...
}
```

And same for modellingQueue array (like children), but it's only for morph meshes (`WHS.Morph`).

**Comment by Noctisdark** [comment]
Retrieve should this root to the old root too ?
