### ISSUE TITLE
[Improve] Adding helpers [Light, Shape, World]

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#75]
We are going to add helpers such as light helper, shadowmap helper, grid, etc.
Such helpers will allow users to simply debug their 3d objects. It is very useful.
![](http://2.bp.blogspot.com/-mUGWmk2uwj8/UiuZsfoxNcI/AAAAAAAAANA/E5NHpHMnalM/s1600/shadow2.png)

- [x] WHS.Light
- [x] WHS.Shape
- [x] WHS.World
- [x] WHS.Camera

[**task#75** branch.](https://github.com/WhitestormJS/whitestorm.js/tree/task%2375)

**Comment by mediafigaro** [comment]
hello, is there any helpers within v2 ? thanks

**Comment by sasha240100** [comment]
@mediafigaro They were moved out of framework core. But you can easily use WHS components with Three.js helpers.
Feel free to ask me if you need some help
