### ISSUE TITLE
[Bug] retrieve() should use addTo().

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#76]
Currently _retrieve()_ function of WHS.Shape and WHS.Light is an opposite to _remove()_, but it is better to use addTo() function, because it is more optimized for adding WHS object to world.

**Do it after _task#75_ is complete!**

**Comment by InsomniacSabbir** [comment]
Hello,
May do this fix ? If so please let me know. Thank you.

**Comment by sasha240100** [comment]
@InsomniacSabbir retrieve is deprecated (user just can use addTo). But, thanks for your suggestion. We have a lot of another interesting stuff to do. If you are interested in participating - you can contact me. I recommend you to register in slack if so - http://whslack.herokuapp.com
