### ISSUE TITLE
[Improve] Follow function for WHS.Camera

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#87]
As for WHS.Shape we should have a follow() function for WHS.Camera class. There will be 2 possible variations: 
 - [x] WHS.Camera flying along **THREE.Curve** and looking at **THREE.Vector3**
 - [x] WHS.Camera flying along **THREE.Curve** and looking at points of another **THREE.Curve**

###### Version:
 - [x] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by Noctisdark** [comment]
Why is this being closed ?

**Comment by sasha240100** [comment]
@Noctisdark https://github.com/WhitestormJS/whitestorm.js/commit/ed002931e5f4c847d8ecb7b949ff0e547da36d69

**Comment by sasha240100** [comment]
@Noctisdark You should be in slack to know latest news.
