### ISSUE TITLE
[Question] Text object font property throws an error

### ISSUE THREAD

**Issue by jeserkin** [WhitestormJS/whitestorm.js#88]
Created a `Text` object and in parameters for `font` property I specified `'Arial'`. For some reason app sends a `GET` request for this font, that obviously returns **404**.

```
three.js:18280 GET http://localhost:63342/3d/app/Arial 404 (Not Found)
  THREE.XHRLoader.load  @ three.js:18280
  THREE.FontLoader.load @ three.js:18327
  WHS.API.loadFont      @ whitestorm.js:1289
  (anonymous function)  @ whitestorm.js:3718
  Text                  @ whitestorm.js:3716
  WHS.World.Text        @ whitestorm.js:3739
  (anonymous function)  @ app.js:8
```

All app script looks like this:
```javascript
var Game = new WHS.World({
  // Type parameters here.

  path_worker: 'physijs_worker.js', // Path to Physijs worker here.
  path_ammo: 'ammo.js' // Path to Ammo.js.
});

var text = Game.Text({
  geometry: {
    text: 'Hello World',
    parameters: {
      font: 'Arial',
      size: 20,
      height: 5,
      curveSegments: 6
    },
    mass: 10,
    material: {
      color: 0x00ff00,
      kind: 'lambert'
    },
    pos: {
      x: -40,
      y: 20,
      z: 0
    }
  }
});

Game.start(); // Start animations and physics simulation.
```
###### Version:
 - [ ] r9 (dev)
 - [x] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [x] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@jeserkin You need to put there path to your typeface font file.

```javascript
var Game = new WHS.World({
  // Type parameters here.

  path_worker: 'physijs_worker.js', // Path to Physijs worker here.
  path_ammo: 'ammo.js' // Path to Ammo.js.
});

var text = Game.Text({
  geometry: {
    text: 'Hello World',
    parameters: {
      font: "assets/fonts/arial.typeface.js", // Here is a path to your font file.
      size: 20,
      height: 5,
      curveSegments: 6
    },
    mass: 10,
    material: {
      color: 0x00ff00,
      kind: 'lambert'
    },
    pos: {
      x: -40,
      y: 20,
      z: 0
    }
  }
});

Game.start(); // Start animations and physics simulation.
``` 

You can generate your typeface file at http://gero3.github.io/facetype.js/
WHS.Text: http://whitestormjs.xyz/?javascript#text

**Comment by jeserkin** [comment]
Then description is incorrect here http://whitestormjs.xyz/?javascript#text. In table it is clearl said, that `font` property is a font name and not a path to typeface.

**Comment by sasha240100** [comment]
@jeserkin Yep. Sorry. Found that. Will fix this typo in description today. Thanks for submitting this issue!
