### ISSUE TITLE
Overload follow function to follow shapes

### ISSUE THREAD

**Issue by ghost** [WhitestormJS/whitestorm.js#89]
I think it would be very nice to make allow function for camera to follow shapes ( sprites )

###### Version:
 - [x] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@ghost Yes, but we plan to separate follow function from main engine (will be deprecated). We plan to make a plugin that will contain such functionality.
