### ISSUE TITLE
Split physi.js file. Make it modular.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#96]
Physi.js should become modular as whitestorm.js is.
**Working branch: "task#96"**
![image](https://cloud.githubusercontent.com/assets/7657429/16365353/6f200ffa-3c06-11e6-9f62-bb6a90b602b6.png)

===TIPS===
- Use es6 import syntax

**Comment by sasha240100** [comment]
Uploaded suggested structure.

**Comment by jackdalton** [comment]
To do:

- [ ] `eventable.js`
- [ ] `index.js`
- [ ] `core/mesh.js`
- [ ] `core/scene.js`
- [ ] `core/material.js`
- [ ] `constraints/PointConstraint.js`
- [ ] `constraints/HingeConstraint.js`
- [ ] `constraints/SliderConstraint.js`
- [ ] `constraints/ConeTwistConstraint.js`
- [ ] `meshes/planeMesh.js`
- [ ] `meshes/heightfieldMesh.js`
- [ ] `meshes/boxMesh.js`
- [ ] `meshes/sphereMesh.js`
- [ ] `meshes/cylinderMesh.js`
- [ ] `meshes/capsuleMesh.js`
- [ ] `meshes/concaveMesh.js`
- [ ] `meshes/convexMesh.js`
- [ ] `vehicle/vehicle.js`
- [ ] `vehicle/tuning.js`
